#!/usr/bin/env python3
"""Generate the config known-key schema from config.defaults.toml."""

from __future__ import annotations

import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = ROOT / "config.defaults.toml"
OUTPUT = ROOT / "Sources/EasyBarApp/Config/ConfigKnownKeySchema.swift"

FREE_FORM_SECTIONS = [
    "app.env",
    "builtins.calendar.composer.alert_labels",
    "builtins.calendar.composer.travel_time_labels",
]

EXTRA_SECTION_KEYS = {
    "theme": ["colors"],
}

EXTRA_SECTIONS = [
    "theme.colors",
]


def normalized_config_line(raw_line: str) -> str | None:
    trimmed = raw_line.strip()
    if not trimmed:
        return None

    if trimmed.startswith("#"):
        uncommented = trimmed[1:].strip()
        if uncommented.startswith("["):
            return uncommented

        if "=" not in uncommented:
            return None

        key = uncommented.split("=", 1)[0].strip()
        if not is_bare_config_key(key):
            return None

        return uncommented

    return trimmed


def is_bare_config_key(key: str) -> bool:
    return re.fullmatch(r"[A-Za-z0-9_]+", key) is not None


def add_section(sections: OrderedDict[str, list[str]], path: str) -> None:
    if path not in sections:
        sections[path] = []

    if not path:
        return

    parts = path.split(".")
    if parts:
        add_key(sections, "", parts[0])

    for index in range(1, len(parts)):
        parent = ".".join(parts[:index])
        child = parts[index]
        add_key(sections, parent, child)


def add_key(sections: OrderedDict[str, list[str]], section: str, key: str) -> None:
    add_section(sections, section)
    if key not in sections[section]:
        sections[section].append(key)


def documented_sections_and_keys(text: str) -> OrderedDict[str, list[str]]:
    sections: OrderedDict[str, list[str]] = OrderedDict()
    section = ""
    add_section(sections, section)

    for raw_line in text.splitlines():
        line = normalized_config_line(raw_line)
        if line is None:
            continue

        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip()
            add_section(sections, section)
            continue

        if "=" not in line:
            continue

        key = line.split("=", 1)[0].strip()
        if key:
            add_key(sections, section, key)

    for extra_section in EXTRA_SECTIONS:
        add_section(sections, extra_section)

    for section_path, keys in EXTRA_SECTION_KEYS.items():
        for key in keys:
            add_key(sections, section_path, key)

    return sections


def render_string_list(values: list[str], indent: str = "    ") -> list[str]:
    if not values:
        return ["[]"]

    if len(values) <= 3 and sum(len(value) + 4 for value in values) <= 80:
        return ["[" + ", ".join(f'\"{value}\"' for value in values) + "]"]

    lines = ["["]
    line = indent
    for value in values:
        item = f'\"{value}\",'
        if len(line) + len(item) + 1 > 100:
            lines.append(line.rstrip())
            line = indent
        line += item + " "
    if line.strip():
        lines.append(line.rstrip())
    lines.append("  ]")
    return lines


def render_schema(sections: OrderedDict[str, list[str]]) -> str:
    lines: list[str] = [
        "import Foundation",
        "",
        "// This file is generated by scripts/generate/config_known_key_schema.py. Do not edit by hand.",
        "// Source of truth: config.defaults.toml.",
        "/// Known config sections and keys used for config typo warnings.",
        "enum ConfigKnownKeySchema {",
        "  private static let placementKeys: Set<String> = [",
        '    "enabled", "position", "order", "group",',
        "  ]",
        "",
        "  private static let widgetStyleKeys: Set<String> = [",
        '    "icon", "text_color", "background_color", "border_color", "border_width",',
        '    "corner_radius", "margin_x", "margin_y", "padding_x", "padding_y", "spacing",',
        '    "opacity",',
        "  ]",
        "",
        "  private static let themeColorKeys = Set(ThemeColorToken.allCases.map(\\.rawValue))",
        "",
        "  private static let knownKeysBySection: [String: Set<String>] = [",
    ]

    for section, keys in sections.items():
        if section == "theme.colors":
            lines.append(f'    "{section}": themeColorKeys,')
            continue

        rendered = render_string_list(keys)
        if len(rendered) == 1:
            lines.append(f'    "{section}": {rendered[0]},')
            continue

        lines.append(f'    "{section}": {rendered[0]}')
        for rendered_line in rendered[1:-1]:
            lines.append(f"      {rendered_line}")
        lines.append(f"      {rendered[-1]},")

    lines.extend([
        "  ]",
        "",
        "  private static let freeFormSections: Set<String> = [",
    ])
    for section in FREE_FORM_SECTIONS:
        lines.append(f'    "{section}",')
    lines.extend([
        "  ]",
        "",
        "  static func isFreeFormSection(_ path: String) -> Bool {",
        "    freeFormSections.contains(path)",
        "  }",
        "",
        "  static func knownKeys(for path: String) -> Set<String> {",
        "    if isBuiltinGroup(path) {",
        "      return placementKeys.union([\"style\"])",
        "    }",
        "",
        "    if isBuiltinGroupStyle(path) {",
        "      return widgetStyleKeys",
        "    }",
        "",
        "    return knownKeysBySection[path] ?? []",
        "  }",
        "",
        "  static func isKnownSection(_ path: String) -> Bool {",
        "    knownKeysBySection[path] != nil",
        "      || freeFormSections.contains(path)",
        "      || isBuiltinGroup(path)",
        "      || isBuiltinGroupStyle(path)",
        "  }",
        "",
        "  private static func isBuiltinGroup(_ path: String) -> Bool {",
        "    let components = path.split(separator: \".\")",
        "    return components.count == 3",
        "      && components[0] == \"builtins\"",
        "      && components[1] == \"groups\"",
        "  }",
        "",
        "  private static func isBuiltinGroupStyle(_ path: String) -> Bool {",
        "    let components = path.split(separator: \".\")",
        "    return components.count == 4",
        "      && components[0] == \"builtins\"",
        "      && components[1] == \"groups\"",
        "      && components[3] == \"style\"",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    sections = documented_sections_and_keys(DEFAULT_CONFIG.read_text(encoding="utf-8"))
    OUTPUT.write_text(render_schema(sections), encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)} from {DEFAULT_CONFIG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
