#!/usr/bin/env python3
"""Generate the configuration reference from config.defaults.toml."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULTS_PATH = ROOT / "config.defaults.toml"
OUTPUT_PATH = ROOT / "docs" / "content" / "configuration" / "reference.md"


@dataclass
class Entry:
    key: str
    value: str
    description: str


@dataclass
class Section:
    name: str
    entries: list[Entry] = field(default_factory=list)


def split_inline_comment(line: str) -> tuple[str, str]:
    """Split one TOML line into content and trailing comment."""
    in_single = False
    in_double = False
    escaped = False

    for index, char in enumerate(line):
        if escaped:
            escaped = False
            continue

        if char == "\\" and in_double:
            escaped = True
            continue

        if char == "'" and not in_double:
            in_single = not in_single
            continue

        if char == '"' and not in_single:
            in_double = not in_double
            continue

        if char == "#" and not in_single and not in_double:
            return line[:index].rstrip(), line[index + 1 :].strip()

    return line.rstrip(), ""


def parse_defaults(path: Path) -> list[Section]:
    sections: list[Section] = []
    current: Section | None = None

    for raw_line in path.read_text().splitlines():
        stripped = raw_line.strip()

        if not stripped or stripped.startswith("#"):
            continue

        content, comment = split_inline_comment(raw_line)
        content = content.strip()

        if not content:
            continue

        if content.startswith("[") and content.endswith("]"):
            current = Section(content[1:-1])
            sections.append(current)
            continue

        if current is None or "=" not in content:
            continue

        key, value = content.split("=", 1)
        current.entries.append(
            Entry(
                key=key.strip(),
                value=value.strip(),
                description=comment,
            )
        )

    return [section for section in sections if section.entries]


def markdown_escape(text: str) -> str:
    return text.replace("|", "\\|")


def code(text: str) -> str:
    escaped = text.replace("`", "\\`")
    return f"`{escaped}`"


def render(sections: list[Section]) -> str:
    lines = [
        "<!--",
        "This file is generated by scripts/generate/config_reference_docs.py.",
        "Do not edit this file by hand. Update config.defaults.toml instead.",
        "-->",
        "",
        "# Configuration Reference",
        "",
        "Generated from `config.defaults.toml`.",
        "",
        "Use this page when you need the exact default value and short description for a supported config key.",
        "For concepts and usage examples, use the hand-written configuration guides.",
        "",
    ]

    for section in sections:
        lines.extend(
            [
                f"## `{section.name}`",
                "",
                "| Key | Default | Description |",
                "| --- | ------- | ----------- |",
            ]
        )

        for entry in section.entries:
            description = markdown_escape(entry.description) if entry.description else ""
            value = code(markdown_escape(entry.value))
            lines.append(f"| {code(entry.key)} | {value} | {description} |")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    sections = parse_defaults(DEFAULTS_PATH)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(sections))


if __name__ == "__main__":
    main()
