#!/usr/bin/env python3
"""Generate the Lua API reference docs from the public LuaLS stub."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
STUB = ROOT / "Sources/EasyBarApp/Lua/easybar_api.lua"
OUT = ROOT / "docs/content/lua/reference"

HEADER = """<!--
This file is generated by scripts/generate/lua_reference_docs.py.
Do not edit this file by hand. Update the LuaLS stub instead.
-->

"""


@dataclass
class AliasValue:
    value: str
    description: str = ""


@dataclass
class AliasDoc:
    name: str
    description: str
    type_expr: str = ""
    values: list[AliasValue] = field(default_factory=list)


@dataclass
class FieldDoc:
    name: str
    type_expr: str
    description: str
    optional: bool


@dataclass
class ClassDoc:
    name: str
    description: str
    modifiers: str = ""
    fields: list[FieldDoc] = field(default_factory=list)


@dataclass
class ParamDoc:
    name: str
    type_expr: str
    description: str
    optional: bool


@dataclass
class FunctionDoc:
    name: str
    description: str
    params: list[ParamDoc] = field(default_factory=list)
    returns: list[str] = field(default_factory=list)


def comment_text(line: str) -> str | None:
    if not line.startswith("---"):
        return None
    return line[3:].strip()


def display_type(type_expr: str) -> str:
    return type_expr.replace("|", "\\|")


def table_escape(value: str) -> str:
    return value.replace("|", "\\|")


def normalize_lua_literal(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1]
    return value


def heading_id(name: str) -> str:
    return f"`{name}`"



@dataclass
class LuaDocParserState:
    aliases: dict[str, AliasDoc] = field(default_factory=dict)
    classes: dict[str, ClassDoc] = field(default_factory=dict)
    functions: dict[str, FunctionDoc] = field(default_factory=dict)
    pending_comments: list[str] = field(default_factory=list)
    pending_function_description: str = ""
    pending_params: list[ParamDoc] = field(default_factory=list)
    pending_returns: list[str] = field(default_factory=list)
    current_alias: AliasDoc | None = None
    current_class: ClassDoc | None = None
    current_function: FunctionDoc | None = None

    def consume(self, raw_line: str) -> None:
        line = raw_line.rstrip()
        comment = comment_text(line)

        if comment is not None and not comment.startswith("@") and not comment.startswith("|"):
            self.pending_comments.append(comment)
            return

        if self.consume_alias(line):
            return
        if self.consume_alias_value(line):
            return
        if self.consume_class(line):
            return
        if self.consume_field(line):
            return
        if self.consume_param(line):
            return
        if self.consume_return(line):
            return
        if self.consume_function(line):
            return

        self.clear_pending_function_context()

    def consume_alias(self, line: str) -> bool:
        alias_match = re.match(r"---@alias\s+(\S+)(?:\s+(.+))?", line)
        if not alias_match:
            return False

        self.current_alias = AliasDoc(
            name=alias_match.group(1),
            description=self.pending_description(),
            type_expr=(alias_match.group(2) or "").strip(),
        )
        self.aliases[self.current_alias.name] = self.current_alias
        self.current_class = None
        self.current_function = None
        self.clear_pending_function_context()
        return True

    def consume_alias_value(self, line: str) -> bool:
        alias_value_match = re.match(r"---\|\s+(.+)", line)
        if not alias_value_match or not self.current_alias:
            return False

        self.current_alias.values.append(
            AliasValue(
                value=normalize_lua_literal(alias_value_match.group(1)),
                description=self.pending_description(),
            )
        )
        self.pending_comments = []
        return True

    def consume_class(self, line: str) -> bool:
        class_match = re.match(r"---@class(?:\s+\(([^)]+)\))?\s+(\S+)", line)
        if not class_match:
            return False

        self.current_class = ClassDoc(
            name=class_match.group(2),
            description=self.pending_description(),
            modifiers=class_match.group(1) or "",
        )
        self.classes[self.current_class.name] = self.current_class
        self.current_alias = None
        self.current_function = None
        self.clear_pending_function_context()
        return True

    def consume_field(self, line: str) -> bool:
        field_match = re.match(r"---@field\s+(\S+)\s+([^\s]+)(?:\s+(.*))?", line)
        if not field_match or not self.current_class:
            return False

        name = field_match.group(1)
        optional = name.endswith("?")
        if optional:
            name = name[:-1]
        self.current_class.fields.append(
            FieldDoc(
                name=name,
                type_expr=field_match.group(2),
                description=(field_match.group(3) or "").strip(),
                optional=optional,
            )
        )
        self.pending_comments = []
        return True

    def consume_param(self, line: str) -> bool:
        param_match = re.match(r"---@param\s+(\S+)\s+(.+)", line)
        if not param_match:
            return False

        name = param_match.group(1)
        optional = name.endswith("?")
        if optional:
            name = name[:-1]
        self.capture_function_description()
        self.pending_params.append(
            ParamDoc(
                name=name,
                type_expr=param_match.group(2).strip(),
                description="",
                optional=optional,
            )
        )
        self.pending_comments = []
        return True

    def consume_return(self, line: str) -> bool:
        return_match = re.match(r"---@return\s+(.+)", line)
        if not return_match:
            return False

        self.capture_function_description()
        self.pending_returns.append(return_match.group(1).strip())
        self.pending_comments = []
        return True

    def consume_function(self, line: str) -> bool:
        function_match = re.match(r"function\s+([A-Za-z0-9_:.]+)\s*\(", line)
        if not function_match:
            return False

        name = function_match.group(1)
        self.current_function = FunctionDoc(
            name=name,
            description=self.pending_function_description or self.pending_description(),
            params=self.pending_params,
            returns=self.pending_returns,
        )
        self.functions[name] = self.current_function
        self.current_alias = None
        self.current_class = None
        self.clear_pending_function_context()
        return True

    def capture_function_description(self) -> None:
        if self.pending_comments and not self.pending_function_description:
            self.pending_function_description = self.pending_description()

    def pending_description(self) -> str:
        return " ".join(self.pending_comments).strip()

    def clear_pending_function_context(self) -> None:
        self.pending_comments = []
        self.pending_function_description = ""
        self.pending_params = []
        self.pending_returns = []


def parse_docs(text: str) -> tuple[dict[str, AliasDoc], dict[str, ClassDoc], dict[str, FunctionDoc]]:
    state = LuaDocParserState()

    for raw_line in text.splitlines():
        state.consume(raw_line)

    add_inline_function_fields(state.classes, state.functions)
    return state.aliases, state.classes, state.functions

def add_inline_function_fields(classes: dict[str, ClassDoc], functions: dict[str, FunctionDoc]) -> None:
    """Turn function-valued class fields into reference docs when no body function exists."""
    easybar = classes.get("EasyBar")
    if easybar:
        for item in easybar.fields:
            if item.type_expr.startswith("fun("):
                name = f"EasyBar.{item.name}"
                functions.setdefault(name, function_from_field(name, item))

    handle = classes.get("EasyBarNodeHandle")
    if handle:
        for item in handle.fields:
            if item.type_expr.startswith("fun("):
                name = f"EasyBarNodeHandle:{item.name}"
                functions.setdefault(name, function_from_field(name, item))


def function_from_field(name: str, field_doc: FieldDoc) -> FunctionDoc:
    params, returns = parse_fun_type(field_doc.type_expr)
    return FunctionDoc(
        name=name,
        description=field_doc.description,
        params=params,
        returns=returns,
    )


def parse_fun_type(type_expr: str) -> tuple[list[ParamDoc], list[str]]:
    match = re.match(r"fun\((.*?)\)(?::\s*(.*))?$", type_expr)
    if not match:
        return [], []

    raw_params = match.group(1).strip()
    raw_returns = (match.group(2) or "").strip()
    params: list[ParamDoc] = []

    if raw_params:
        for item in split_top_level(raw_params, ","):
            item = item.strip()
            if not item or ":" not in item:
                continue
            name, param_type = item.split(":", 1)
            name = name.strip()
            optional = name.endswith("?")
            if optional:
                name = name[:-1]
            params.append(ParamDoc(name=name, type_expr=param_type.strip(), description="", optional=optional))

    returns = [part.strip() for part in split_top_level(raw_returns, ",") if part.strip()]
    return params, returns


def split_top_level(text: str, delimiter: str) -> list[str]:
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for char in text:
        if char == "(":
            depth += 1
        elif char == ")" and depth > 0:
            depth -= 1
        if char == delimiter and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
    parts.append("".join(current))
    return parts


def write_index() -> None:
    content = HEADER + """# Lua Reference

This section is generated from the EasyBar LuaLS stub and is meant to answer
\"what is the exact API surface?\" quickly.

Use these pages for exact types, event names, and property tables. For usage
patterns and architecture, use the hand-written guides.

## Generated pages

- [Functions](functions.md)
  Top-level `easybar.*` calls and node handle methods.
- [Node kinds](node-kinds.md)
  Literal kind values plus the `easybar.kind.*` namespace.
- [Events](events.md)
  Runtime event names, payloads, and the `easybar.events.*` namespace.
- [Properties](properties.md)
  Property tables used by nodes, labels, icons, popups, and layout styling.

## Recommended reading order

1. Start with [Lua Overview](../overview.md) for the node-based mental model.
2. Read [Functions](functions.md) to learn how widgets are created and updated.
3. Keep [Events](events.md) and [Properties](properties.md) open while building widgets.

## Source of truth

The source of truth is the public LuaLS stub:

```text
Sources/EasyBarApp/Lua/easybar_api.lua
```

If this reference is wrong, update the stub and regenerate the docs.
"""
    (OUT / "index.md").write_text(content)


def render_alias(alias: AliasDoc) -> list[str]:
    lines = [f"## {heading_id(alias.name)}", ""]
    if alias.description:
      lines += [alias.description, ""]
    if alias.type_expr:
        lines += ["| Value |", "| ----- |", f"| `{display_type(alias.type_expr)}` |", ""]
    if alias.values:
        lines += ["| Value | Meaning |", "| ----- | ------- |"]
        for item in alias.values:
            lines.append(f"| `{table_escape(item.value)}` | {table_escape(item.description)} |")
        lines.append("")
    return lines


def render_class(cls: ClassDoc) -> list[str]:
    lines = [f"## {heading_id(cls.name)}", ""]
    if cls.modifiers:
        lines += [f"Modifiers: `{cls.modifiers}`.", ""]
    if cls.description:
        lines += [cls.description, ""]
    if cls.fields:
        lines += ["| Property | Type | Description |", "| -------- | ---- | ----------- |"]
        for item in cls.fields:
            name = f"`{item.name}`"
            if item.optional:
                name += " _(optional)_"
            lines.append(
                f"| {name} | `{display_type(item.type_expr)}` | {table_escape(item.description)} |"
            )
        lines.append("")
    return lines


def render_function(fn: FunctionDoc) -> list[str]:
    lines = [f"## {heading_id(fn.name)}", ""]
    if fn.description:
        lines += [fn.description, ""]
    if fn.params:
        lines += ["### Parameters", "", "| Name | Type | Description |", "| ---- | ---- | ----------- |"]
        for param in fn.params:
            name = f"`{param.name}`"
            if param.optional:
                name += " _(optional)_"
            lines.append(f"| {name} | `{display_type(param.type_expr)}` | {table_escape(param.description)} |")
        lines.append("")
    if fn.returns:
        lines += ["### Returns", ""]
        for ret in fn.returns:
            lines.append(f"- `{display_type(ret)}`")
        lines.append("")
    return lines


def write_functions(functions: dict[str, FunctionDoc]) -> None:
    preferred = [
        "EasyBar.add", "EasyBar.clear_defaults", "EasyBar.default", "EasyBar.exec",
        "EasyBar.exec_async", "EasyBar.get", "EasyBar.log", "EasyBar.remove",
        "EasyBar.set", "EasyBar.subscribe", "EasyBar.unset",
        "EasyBarNodeHandle:get", "EasyBarNodeHandle:remove", "EasyBarNodeHandle:set",
        "EasyBarNodeHandle:subscribe", "EasyBarNodeHandle:unset",
    ]
    ordered = [functions[name] for name in preferred if name in functions]
    seen = {fn.name for fn in ordered}
    ordered += [functions[name] for name in sorted(functions) if name not in seen]

    lines = [HEADER, "# Functions", "", "Generated from LuaLS function annotations.", ""]
    for fn in ordered:
        lines.extend(render_function(fn))
    (OUT / "functions.md").write_text("\n".join(lines).rstrip() + "\n")


def write_node_kinds(aliases: dict[str, AliasDoc], classes: dict[str, ClassDoc]) -> None:
    lines = [HEADER, "# Node Kinds", "", "Generated from LuaLS aliases and namespace fields.", ""]
    for name in ["EasyBarKind"]:
        if name in aliases:
            lines.extend(render_alias(aliases[name]))
    for name in ["EasyBarKinds"]:
        if name in classes:
            lines.extend(render_class(classes[name]))
    (OUT / "node-kinds.md").write_text("\n".join(lines).rstrip() + "\n")


def write_events(aliases: dict[str, AliasDoc], classes: dict[str, ClassDoc]) -> None:
    names = [name for name in aliases if "Event" in name or name in {"EasyBarMouseButton", "EasyBarScrollDirection"}]
    class_names = [name for name in classes if "Event" in name or name.endswith("EventData")]

    lines = [HEADER, "# Events", "", "Generated from LuaLS aliases and event namespace classes.", ""]
    for name in sorted(names):
        lines.extend(render_alias(aliases[name]))
    for name in sorted(class_names):
        lines.extend(render_class(classes[name]))
    (OUT / "events.md").write_text("\n".join(lines).rstrip() + "\n")


def write_properties(aliases: dict[str, AliasDoc], classes: dict[str, ClassDoc]) -> None:
    property_aliases = [
        "EasyBarBoolLike", "EasyBarIconLike", "EasyBarLabelLike",
        "EasyBarPosition", "EasyBarRootPosition",
    ]
    property_classes = [
        "EasyBarBackgroundProps", "EasyBarFontProps", "EasyBarIconProps",
        "EasyBarImageProps", "EasyBarLabelProps", "EasyBarMarginProps",
        "EasyBarNodeProps", "EasyBarPopupProps",
    ]

    lines = [HEADER, "# Properties", "", "Generated from LuaLS class and field annotations.", ""]
    lines += ["## Common Value Types", ""]
    for name in property_aliases:
        if name in aliases:
            lines.extend(render_alias(aliases[name]))
    lines += ["## Property Tables", ""]
    for name in property_classes:
        if name in classes:
            lines.extend(render_class(classes[name]))
    (OUT / "properties.md").write_text("\n".join(lines).rstrip() + "\n")


def main() -> int:
    aliases, classes, functions = parse_docs(STUB.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    write_index()
    write_functions(functions)
    write_node_kinds(aliases, classes)
    write_events(aliases, classes)
    write_properties(aliases, classes)
    print(f"Generated Lua reference docs in {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


