#!/usr/bin/env python3

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "Sources/EasyBarApp/Theme/theme_tokens.json"
SWIFT_OUTPUT_PATH = ROOT / "Sources/EasyBarApp/Theme/ThemeColorToken.swift"
LUA_RUNTIME_OUTPUT_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar/theme_tokens.lua"
LUA_API_THEMES_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar_api.themes.lua"
LUA_API_BASE_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar_api.base.lua"
LUA_API_THEMES_START = "-- GENERATED SECTION: easybar.themes"
LUA_API_THEMES_END = "-- END GENERATED SECTION: easybar.themes"


def repo_relative(path: Path) -> str:
    """Return a repository-relative display path for generated artifacts."""
    return str(path.relative_to(ROOT))


def load_manifest() -> dict:
    """Load the theme token manifest used to generate Swift and Lua artifacts."""
    return json.loads(MANIFEST_PATH.read_text())


def render_swift_enum(tokens: list[dict]) -> str:
    """Render the generated Swift token enum."""
    lines = [
        "import Foundation",
        "",
        "// This file is generated by scripts/generate_theme_tokens.py. Do not edit by hand.",
        "/// Supported shared theme color tokens.",
        "enum ThemeColorToken: String, CaseIterable {",
    ]

    for token in tokens:
      swift_case = token["swiftCase"]
      raw_name = token["name"]
      if swift_case == raw_name:
          lines.append(f"  case {swift_case}")
      else:
          lines.append(f'  case {swift_case} = "{raw_name}"')

    lines.extend([
        "",
        "  /// Theme reference string used in config and Lua APIs.",
        "  var reference: String {",
        '    "theme.\\(rawValue)"',
        "  }",
        "",
        "  /// Returns the token for one user-provided reference suffix.",
        "  init?(normalizedToken: String) {",
        "    self.init(rawValue: normalizedToken.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_lua_theme_tokens(tokens: list[dict]) -> str:
    """Render the generated Lua theme token module."""
    lines = [
        "--- Module contract:",
        "--- Owns generated EasyBar theme token names shared across Lua runtime modules.",
        "--- Returns one table containing `keys` in stable public order.",
        "-- This file is generated by scripts/generate_theme_tokens.py. Do not edit by hand.",
        "--- Theme token module table.",
        "local M = {}",
        "",
        "--- Public theme token names exposed to Lua widgets and docs.",
        "M.keys = {",
    ]
    for token in tokens:
        lines.append(f'\t"{token["name"]}",')
    lines.extend([
        "}",
        "",
        "return M",
        "",
    ])
    return "\n".join(lines)


def render_lua_api_themes(tokens: list[dict]) -> str:
    """Render the generated EmmyLua theme annotations."""
    lines = [
        "-- EasyBar generated theme stub. Do not edit by hand.",
        "-- Source of truth: Sources/EasyBarApp/Theme/theme_tokens.json",
        "-- Regenerate with: scripts/generate_theme_tokens.py",
        "---Resolved active theme colors.",
        "---@class EasyBarThemeColors",
    ]
    for token in tokens:
        lines.append(f'---@field {token["name"]} string {token["doc"]}')

    lines.extend([
        "",
        "---Theme reference strings accepted by color fields.",
        "---These always mirror the active `EasyBarThemeColors` keys.",
        "---@class EasyBarThemeRefs",
    ])
    for token in tokens:
        lines.append(
            f'---@field {token["name"]} string Reference string for `theme.{token["name"]}`.'
        )

    lines.extend([
        "",
        "---Active resolved theme exposed to Lua widgets.",
        "---Use `theme.colors.<token>` for resolved hex colors and `theme.ref.<token>` when you want to keep a node color bound to the active theme.",
        "---@class EasyBarTheme",
        "---@field name string Active theme name from `[theme].name`.",
        "---@field colors EasyBarThemeColors Resolved theme colors.",
        "---@field ref EasyBarThemeRefs Theme reference strings such as `theme.text`.",
        "",
    ])
    return "\n".join(lines)


def replace_generated_theme_section(base_text: str, generated: str) -> str:
    """Replace the theme section inside the Lua API base stub."""
    pattern = re.compile(
        rf"{re.escape(LUA_API_THEMES_START)}.*?{re.escape(LUA_API_THEMES_END)}",
        flags=re.DOTALL,
    )
    replacement = f"{LUA_API_THEMES_START}\n{generated.rstrip()}\n{LUA_API_THEMES_END}"
    updated, count = pattern.subn(replacement, base_text, count=1)
    if count != 1:
        raise SystemExit("could not find generated theme API insertion markers in easybar_api.base.lua")
    return updated.rstrip() + "\n"


def main() -> None:
    manifest = load_manifest()
    tokens = manifest["tokens"]

    SWIFT_OUTPUT_PATH.write_text(render_swift_enum(tokens))
    LUA_RUNTIME_OUTPUT_PATH.write_text(render_lua_theme_tokens(tokens))

    generated_themes = render_lua_api_themes(tokens)
    LUA_API_THEMES_PATH.write_text(generated_themes)

    base_text = LUA_API_BASE_PATH.read_text()
    LUA_API_BASE_PATH.write_text(replace_generated_theme_section(base_text, generated_themes))

    print("Generated theme token artifacts:")
    for path in (
        SWIFT_OUTPUT_PATH,
        LUA_RUNTIME_OUTPUT_PATH,
        LUA_API_THEMES_PATH,
        LUA_API_BASE_PATH,
    ):
        print(f"- {repo_relative(path)}")


if __name__ == "__main__":
    main()


