import EasyBarShared

typealias NativeCalendarPopupSectionKind = CalendarAgentSectionKind
typealias NativeCalendarPopupSection = CalendarAgentSection
typealias NativeCalendarPopupItem = CalendarAgentItem
typealias NativeCalendarEvent = CalendarAgentEvent
