import EasyBarConfigSchema
import Foundation

private let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

private enum GeneratorError: Error, CustomStringConvertible {
  case unknownCommand(String)
  case writeFailed(String)

  var description: String {
    switch self {
    case .unknownCommand(let command):
      "unknown command: \(command)"
    case .writeFailed(let path):
      "failed to write \(path)"
    }
  }
}

private enum CatalogValue {
  case activeDefault(String)
  case example(String)
}

private struct CatalogEntry {
  let key: String
  let value: CatalogValue
  let description: String
}

private func write(_ text: String, to relativePath: String) throws {
  let url = root.appendingPathComponent(relativePath)
  try FileManager.default.createDirectory(
    at: url.deletingLastPathComponent(),
    withIntermediateDirectories: true
  )
  try text.write(to: url, atomically: true, encoding: .utf8)
  print("Generated \(relativePath)")
}

private func renderDefaults() -> String {
  let lines = ConfigSchemaRegistry.lines.map { line in
    switch line {
    case .blank:
      return ""
    case .comment(let text):
      return text
    case .section(let name, let commented, let prefix, _):
      return "\(commented ? prefix : "")[\(name)]"
    case .entry(let key, let value, let description, let commented, let prefix, _):
      let suffix = description.isEmpty ? "" : " # \(description)"
      return "\(commented ? prefix : "")\(key) = \(value)\(suffix)"
    case .optionalEntry(let key, let value, let description):
      let suffix = description.isEmpty ? "" : " # \(description)"
      return "# \(key) = \(value)\(suffix)"
    }
  }

  return lines.joined(separator: "\n") + "\n"
}

private func documentedSections() -> [(name: String, entries: [CatalogEntry])] {
  var result: [(name: String, entries: [CatalogEntry])] = []
  var currentName: String?
  var currentSectionIsCommented = false
  var currentSectionIsDocumented = false
  var currentEntries: [CatalogEntry] = []

  func flush() {
    guard let name = currentName, !currentEntries.isEmpty else { return }
    result.append((name, currentEntries))
    currentEntries.removeAll()
  }

  for line in ConfigSchemaRegistry.lines {
    switch line {
    case .section(let name, let commented, _, let documented):
      flush()
      currentName = name
      currentSectionIsCommented = commented
      currentSectionIsDocumented = documented

    case .entry(let key, let value, let description, let commented, _, let documented):
      guard currentSectionIsDocumented, documented else { continue }
      let catalogValue: CatalogValue =
        currentSectionIsCommented || commented ? .example(value) : .activeDefault(value)
      currentEntries.append(
        CatalogEntry(
          key: key,
          value: catalogValue,
          description: description
        ))

    case .optionalEntry(let key, let value, let description):
      guard currentSectionIsDocumented else { continue }
      currentEntries.append(
        CatalogEntry(
          key: key,
          value: .example(value),
          description: description
        ))

    case .blank, .comment:
      continue
    }
  }

  flush()
  return result
}

private func markdownEscape(_ value: String) -> String {
  value.replacingOccurrences(of: "|", with: "\\|")
}

private func code(_ value: String) -> String {
  "`\(value.replacingOccurrences(of: "`", with: "\\`"))`"
}

private func renderConfigDocs() -> String {
  var lines = [
    "<!--",
    "This file is generated by EasyBarGenerateConfig config-docs.",
    "Do not edit this file by hand. Update the EasyBarConfigSchema module instead.",
    "-->",
    "",
    "# Configuration Reference",
    "",
    "Generated from the `EasyBarConfigSchema` module.",
    "",
    "Use this page when you need the exact default value and short description for a supported config key.",
    "For concepts and usage examples, use the hand-written configuration guides.",
    "",
    "`Not set` means the shipped default config omits that key. The Example column shows a commented value that can be enabled explicitly; the description may also document a derived runtime fallback.",
    "",
  ]

  for section in documentedSections() {
    lines.append("## `\(section.name)`")
    lines.append("")
    lines.append("| Key | Default | Example | Description |")
    lines.append("| --- | ------- | ------- | ----------- |")

    for entry in section.entries {
      let description = markdownEscape(entry.description)
      let defaultValue: String
      let exampleValue: String

      switch entry.value {
      case .activeDefault(let value):
        defaultValue = code(markdownEscape(value))
        exampleValue = "—"
      case .example(let value):
        defaultValue = "Not set"
        exampleValue = code(markdownEscape(value))
      }

      lines.append(
        "| \(code(entry.key)) | \(defaultValue) | \(exampleValue) | \(description) |"
      )
    }

    lines.append("")
  }

  return lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
}

private func generateDefaults() throws {
  try write(renderDefaults(), to: "config.defaults.toml")
}

private func generateDocs() throws {
  try write(renderConfigDocs(), to: "docs/content/configuration/reference.md")
}

private func generateAll() throws {
  try generateDefaults()
  try generateDocs()
}

private func main() throws {
  let command = CommandLine.arguments.dropFirst().first ?? "all"

  switch command {
  case "all":
    try generateAll()
  case "defaults":
    try generateDefaults()
  case "config-docs":
    try generateDocs()
  default:
    throw GeneratorError.unknownCommand(command)
  }
}

do {
  try main()
} catch {
  FileHandle.standardError.write(Data("\(error)\n".utf8))
  exit(1)
}
