import EasyBarConfigSchema
import Foundation

private let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

private enum GeneratorError: Error, CustomStringConvertible {
  case unknownCommand(String)
  case writeFailed(String)

  var description: String {
    switch self {
    case .unknownCommand(let command):
      "unknown command: \(command)"
    case .writeFailed(let path):
      "failed to write \(path)"
    }
  }
}

private struct CatalogEntry {
  let section: String
  let key: String
  let value: String
  let description: String
  let commented: Bool
}

private func write(_ text: String, to relativePath: String) throws {
  let url = root.appendingPathComponent(relativePath)
  try FileManager.default.createDirectory(
    at: url.deletingLastPathComponent(),
    withIntermediateDirectories: true
  )
  try text.write(to: url, atomically: true, encoding: .utf8)
  print("Generated \(relativePath)")
}

private func renderDefaults() -> String {
  let lines = ConfigSchemaRegistry.lines.map { line in
    switch line {
    case .blank:
      return ""
    case .comment(let text):
      return text
    case .section(let name, let commented, let prefix):
      return "\(commented ? prefix : "")[\(name)]"
    case .entry(let key, let value, let description, let commented, let prefix):
      let suffix = description.isEmpty ? "" : " # \(description)"
      return "\(commented ? prefix : "")\(key) = \(value)\(suffix)"
    }
  }

  return lines.joined(separator: "\n") + "\n"
}

private func catalogEntries(includeCommented: Bool) -> [(section: String, entry: CatalogEntry)] {
  var currentSection = ""
  var entries: [(section: String, entry: CatalogEntry)] = []

  for line in ConfigSchemaRegistry.lines {
    switch line {
    case .section(let name, _, _):
      currentSection = name
    case .entry(let key, let value, let description, let commented, _):
      guard includeCommented || !commented else { continue }
      entries.append(
        (
          currentSection,
          CatalogEntry(
            section: currentSection,
            key: key,
            value: value,
            description: description,
            commented: commented
          )
        ))
    case .blank, .comment:
      continue
    }
  }

  return entries
}

private func activeSections() -> [(name: String, entries: [CatalogEntry])] {
  var result: [(name: String, entries: [CatalogEntry])] = []
  var currentName: String?
  var currentEntries: [CatalogEntry] = []

  func flush() {
    guard let name = currentName, !currentEntries.isEmpty else { return }
    result.append((name, currentEntries))
    currentEntries.removeAll()
  }

  for line in ConfigSchemaRegistry.lines {
    switch line {
    case .section(let name, let commented, _):
      flush()
      currentName = commented ? nil : name
    case .entry(let key, let value, let description, let commented, _):
      guard let section = currentName, !commented else { continue }
      currentEntries.append(
        CatalogEntry(
          section: section,
          key: key,
          value: value,
          description: description,
          commented: false
        ))
    case .blank, .comment:
      continue
    }
  }

  flush()
  return result
}

private func markdownEscape(_ value: String) -> String {
  value.replacingOccurrences(of: "|", with: "\\|")
}

private func code(_ value: String) -> String {
  "`\(value.replacingOccurrences(of: "`", with: "\\`"))`"
}

private func renderConfigDocs() -> String {
  var lines = [
    "<!--",
    "This file is generated by EasyBarGenerateConfig config-docs.",
    "Do not edit this file by hand. Update Sources/EasyBarConfigSchema/ConfigSchema.swift instead.",
    "-->",
    "",
    "# Configuration Reference",
    "",
    "Generated from `Sources/EasyBarConfigSchema/ConfigSchema.swift`.",
    "",
    "Use this page when you need the exact default value and short description for a supported config key.",
    "For concepts and usage examples, use the hand-written configuration guides.",
    "",
  ]

  for section in activeSections() {
    lines.append("## `\(section.name)`")
    lines.append("")
    lines.append("| Key | Default | Description |")
    lines.append("| --- | ------- | ----------- |")

    for entry in section.entries {
      let description = markdownEscape(entry.description)
      let value = code(markdownEscape(entry.value))
      lines.append("| \(code(entry.key)) | \(value) | \(description) |")
    }

    lines.append("")
  }

  return lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
}

private func generateDefaults() throws {
  try write(renderDefaults(), to: "config.defaults.toml")
}

private func generateDocs() throws {
  try write(renderConfigDocs(), to: "docs/content/configuration/reference.md")
}

private func generateAll() throws {
  try generateDefaults()
  try generateDocs()
}

private func main() throws {
  let command = CommandLine.arguments.dropFirst().first ?? "all"

  switch command {
  case "all":
    try generateAll()
  case "defaults":
    try generateDefaults()
  case "config-docs":
    try generateDocs()
  default:
    throw GeneratorError.unknownCommand(command)
  }
}

do {
  try main()
} catch {
  FileHandle.standardError.write(Data("\(error)\n".utf8))
  exit(1)
}
