[app]
watch_config = false

[agents.network]
refresh_interval_seconds = 60

[builtins.spaces]
enabled = true

[builtins.groups.system]
position = "right"
order = 20

[builtins.groups.system.style]

[builtins.battery]
enabled = true
group = "system"

[builtins.wifi]
enabled = true
group = "system"

[builtins.calendar]
enabled = true
