-- EasyBar generated event stub. Do not edit by hand.
-- Source of truth: Sources/EasyBarApp/Events/event_catalog.json
-- Regenerate with: scripts/generate/artifacts.py event-catalog
---Canonical runtime event-name strings carried inside `EasyBarEventToken.name`.
---In normal widget code, prefer `easybar.events.*` tokens over comparing raw strings.
---@alias EasyBarEventName
---Internal timer callback name delivered to the widget whose own `interval` schedule elapsed.
---| '"interval"'
---Fired when EasyBar or `easybar` triggers a manual refresh.
---| '"forced"'
---Fired after the system wakes from sleep.
---| '"system_woke"'
---Fired when the macOS user session becomes active.
---| '"session_active"'
---Fired when the macOS user session resigns active status.
---| '"session_inactive"'
---Fired before the system goes to sleep.
---| '"sleep"'
---Fired when the active macOS space changes.
---| '"space_change"'
---Fired when the frontmost app changes.
---| '"app_switch"'
---Fired when attached displays change.
---| '"display_change"'
---Fired when the power source changes.
---| '"power_source_change"'
---Fired when charging starts or stops.
---| '"charging_state_change"'
---Fired when Wi-Fi state or SSID changes.
---| '"wifi_change"'
---Fired when network routing or tunnel state changes.
---| '"network_change"'
---Fired when output volume changes.
---| '"volume_change"'
---Fired when mute state changes.
---| '"mute_change"'
---Fired once per minute.
---| '"minute_tick"'
---Fired once per second.
---| '"second_tick"'
---Fired when the calendar snapshot updates.
---| '"calendar_change"'
---Fired when workspace focus changes.
---| '"focus_change"'
---Fired when workspace layout or selection changes.
---| '"workspace_change"'
---Fired when the AeroSpace layout mode changes.
---| '"space_mode_change"'
---Fired when the pointer enters the subscribed node frame.
---| '"mouse.entered"'
---Fired when the pointer leaves the subscribed node frame.
---| '"mouse.exited"'
---Fired when the subscribed node is clicked.
---| '"mouse.clicked"'
---Fired on mouse button press over the subscribed node.
---| '"mouse.down"'
---Fired on mouse button release over the subscribed node.
---| '"mouse.up"'
---Fired when the pointer scrolls over the subscribed node.
---| '"mouse.scrolled"'
---Fired while a slider is being previewed or dragged.
---| '"slider.preview"'
---Fired when a slider value is committed.
---| '"slider.changed"'

---Structured network-specific fields that may be present on network-related events.
---@class EasyBarNetworkEventData
---@field primary_interface_is_tunnel? boolean Whether the current primary network interface is a tunnel.
---@field interface_name? string The network interface name when provided.

---Structured power-specific fields that may be present on charging or power-source events.
---@class EasyBarPowerEventData
---@field charging? boolean Whether the current power source is charging.

---Structured audio-specific fields that may be present on mute or volume events.
---@class EasyBarAudioEventData
---@field muted? boolean Whether the current audio output is muted.
---@field value? number The current audio-related value when provided.

---The event payload object delivered to event handlers.
---Different event families populate different optional fields.
---@class EasyBarEvent
---@field name string The dispatched event name.
---@field source? string Diagnostic source that caused EasyBar to emit the event.
---@field widget_id? string The subscribed widget id receiving the event.
---@field target_widget_id? string The concrete node id that received the interaction.
---@field app_name? string The focused app name for app-switch style events.
---@field button? EasyBarMouseButton|string The mouse button name, usually `left`, `right`, or `middle`.
---@field direction? EasyBarScrollDirection|string The scroll direction, usually `up`, `down`, `left`, or `right`.
---@field value? number|string|boolean The event value for slider and driver updates.
---@field delta_x? number Horizontal scroll delta.
---@field delta_y? number Vertical scroll delta.
---@field network? EasyBarNetworkEventData Structured network event data.
---@field power? EasyBarPowerEventData Structured power event data.
---@field audio? EasyBarAudioEventData Structured audio event data.

---The callback signature used by `node:subscribe(...)` and `easybar.subscribe(...)`.
---@alias EasyBarEventHandler fun(event: EasyBarEvent)

---Opaque subscribe token object passed through from `easybar.events.*`.
---@class EasyBarEventToken
---@field name EasyBarEventName The canonical runtime event name sent by EasyBar.

---Convenience constants mirrored under `easybar.events.mouse.buttons`.
---@class EasyBarMouseButtons
---@field left EasyBarMouseButton Matches the primary mouse button.
---@field right EasyBarMouseButton Matches the secondary mouse button.
---@field middle EasyBarMouseButton Matches the middle mouse button.

---Convenience constants mirrored under `easybar.events.mouse.directions`.
---@class EasyBarScrollDirections
---@field up EasyBarScrollDirection Matches upward scrolling.
---@field down EasyBarScrollDirection Matches downward scrolling.
---@field left EasyBarScrollDirection Matches leftward scrolling.
---@field right EasyBarScrollDirection Matches rightward scrolling.

---Mouse-specific interaction tokens and convenience constants nested under `easybar.events.mouse`.
---@class EasyBarMouseEvents
---@field entered? EasyBarEventToken Fired when the pointer enters the subscribed node frame.
---@field exited? EasyBarEventToken Fired when the pointer leaves the subscribed node frame.
---@field clicked? EasyBarEventToken Fired when the subscribed node is clicked.
---@field down? EasyBarEventToken Fired on mouse button press over the subscribed node.
---@field up? EasyBarEventToken Fired on mouse button release over the subscribed node.
---@field scrolled? EasyBarEventToken Fired when the pointer scrolls over the subscribed node.
---@field left_button EasyBarMouseButton Constant for `event.button == "left"`.
---@field right_button EasyBarMouseButton Constant for `event.button == "right"`.
---@field middle_button EasyBarMouseButton Constant for `event.button == "middle"`.
---@field up_scroll EasyBarScrollDirection Constant for `event.direction == "up"`.
---@field down_scroll EasyBarScrollDirection Constant for `event.direction == "down"`.
---@field left_scroll EasyBarScrollDirection Constant for `event.direction == "left"`.
---@field right_scroll EasyBarScrollDirection Constant for `event.direction == "right"`.
---@field buttons EasyBarMouseButtons Nested mouse-button constants.
---@field directions EasyBarScrollDirections Nested scroll-direction constants.

---Slider-specific interaction tokens nested under `easybar.events.slider`.
---@class EasyBarSliderEvents
---@field preview? EasyBarEventToken Fired while a slider is being previewed or dragged.
---@field changed? EasyBarEventToken Fired when a slider value is committed.

---Namespace object exposed as `easybar.events`.
---Use these tokens when subscribing widgets instead of hard-coding event-name strings.
---@class EasyBarEvents
---@field forced? EasyBarEventToken Fired when EasyBar or `easybar` triggers a manual refresh.
---@field system_woke? EasyBarEventToken Fired after the system wakes from sleep.
---@field session_active? EasyBarEventToken Fired when the macOS user session becomes active.
---@field session_inactive? EasyBarEventToken Fired when the macOS user session resigns active status.
---@field sleep? EasyBarEventToken Fired before the system goes to sleep.
---@field space_change? EasyBarEventToken Fired when the active macOS space changes.
---@field app_switch? EasyBarEventToken Fired when the frontmost app changes.
---@field display_change? EasyBarEventToken Fired when attached displays change.
---@field power_source_change? EasyBarEventToken Fired when the power source changes.
---@field charging_state_change? EasyBarEventToken Fired when charging starts or stops.
---@field wifi_change? EasyBarEventToken Fired when Wi-Fi state or SSID changes.
---@field network_change? EasyBarEventToken Fired when network routing or tunnel state changes.
---@field volume_change? EasyBarEventToken Fired when output volume changes.
---@field mute_change? EasyBarEventToken Fired when mute state changes.
---@field minute_tick? EasyBarEventToken Fired once per minute.
---@field second_tick? EasyBarEventToken Fired once per second.
---@field calendar_change? EasyBarEventToken Fired when the calendar snapshot updates.
---@field focus_change? EasyBarEventToken Fired when workspace focus changes.
---@field workspace_change? EasyBarEventToken Fired when workspace layout or selection changes.
---@field space_mode_change? EasyBarEventToken Fired when the AeroSpace layout mode changes.
---@field mouse? EasyBarMouseEvents Mouse interaction event tokens and constants.
---@field slider? EasyBarSliderEvents Slider interaction event tokens.
