import Foundation

// This file is generated by scripts/generate_theme_tokens.py. Do not edit by hand.
/// Supported shared theme color tokens.
enum ThemeColorToken: String, CaseIterable {
  case background
  case surface
  case surfaceElevated = "surface_elevated"
  case surfaceHover = "surface_hover"
  case text
  case textSecondary = "text_secondary"
  case textTertiary = "text_tertiary"
  case muted
  case mutedSecondary = "muted_secondary"
  case outsideMonth = "outside_month"
  case accent
  case accentSecondary = "accent_secondary"
  case accentSoft = "accent_soft"
  case success
  case successSecondary = "success_secondary"
  case warning
  case orange
  case error
  case danger
  case border
  case borderStrong = "border_strong"
  case borderSubtle = "border_subtle"
  case selectionText = "selection_text"
  case selectionBackground = "selection_background"
  case transparent
  case overlayOutline = "overlay_outline"
  case overlayText = "overlay_text"
  case todayButtonBorder = "today_button_border"

  /// Theme reference string used in config and Lua APIs.
  var reference: String {
    "theme.\(rawValue)"
  }

  /// Returns the token for one user-provided reference suffix.
  init?(normalizedToken: String) {
    self.init(rawValue: normalizedToken.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
  }
}
