import Foundation

// This file is generated by scripts/generate/config_known_key_schema.py. Do not edit by hand.
// Source of truth: config.defaults.toml.
/// Known config sections and keys used for config typo warnings.
enum ConfigKnownKeySchema {
  private static let placementKeys: Set<String> = [
    "enabled", "position", "order", "group",
  ]

  private static let widgetStyleKeys: Set<String> = [
    "icon", "text_color", "background_color", "border_color", "border_width",
    "corner_radius", "margin_x", "margin_y", "padding_x", "padding_y", "spacing",
    "opacity",
  ]

  private static let themeColorKeys = Set(ThemeColorToken.allCases.map(\.rawValue))

  private static let knownKeysBySection: [String: Set<String>] = [
    "": [
      "app", "theme", "logging", "agents", "bar", "builtins",
    ],
    "app": [
      "widgets_dir", "lua_path", "lua_socket_path", "watch_config", "lock_dir",
      "widget_editor_stub_path", "develop", "env", "lua_commands",
    ],
    "app.env": ["PATH"],
    "app.lua_commands": ["timeout_seconds", "max_output_bytes", "max_async_jobs"],
    "theme": ["name", "themes_dir", "colors"],
    "logging": ["enabled", "level", "directory"],
    "agents.calendar": ["enabled", "socket_path"],
    "agents": ["calendar", "network"],
    "agents.network": [
      "enabled", "socket_path", "refresh_interval_seconds",
      "allow_unauthorized_non_sensitive_fields",
    ],
    "bar": [
      "height", "padding_x", "extend_behind_notch", "colors",
    ],
    "bar.colors": ["background", "border"],
    "builtins.spaces": [
      "enabled", "position", "order", "icon", "text_color", "background_color", "border_color",
      "border_width", "corner_radius", "margin_x", "margin_y", "padding_x", "padding_y", "spacing",
      "opacity", "layout", "text", "icons", "colors",
    ],
    "builtins": [
      "spaces", "front_app", "aerospace_mode", "cpu", "groups", "battery", "wifi", "volume",
      "calendar", "time", "date",
    ],
    "builtins.spaces.layout": [
      "spacing", "hide_empty", "padding_x", "padding_y", "margin_x", "margin_y", "corner_radius",
      "focused_corner_radius", "focused_scale", "inactive_opacity", "max_icons", "show_label",
      "show_icons", "show_only_focused_label", "collapse_inactive", "collapsed_padding_x",
      "collapsed_padding_y", "click_to_focus_space", "click_to_focus_app",
    ],
    "builtins.spaces.text": [
      "size", "weight", "focused_color", "inactive_color",
    ],
    "builtins.spaces.icons": [
      "size", "spacing", "corner_radius", "focused_app_size", "border_width",
      "focused_app_border_width",
    ],
    "builtins.spaces.colors": [
      "active_background", "inactive_background", "active_border", "inactive_border",
      "focused_app_border",
    ],
    "builtins.front_app": [
      "enabled", "position", "order", "style", "content",
    ],
    "builtins.front_app.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.front_app.content": [
      "show_icon", "show_name", "fallback_text", "icon_size", "icon_corner_radius",
    ],
    "builtins.aerospace_mode": [
      "enabled", "position", "order", "style", "content",
    ],
    "builtins.aerospace_mode.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.aerospace_mode.content": [
      "show_icon", "show_text", "h_tiles_icon", "v_tiles_icon", "h_accordion_icon",
      "v_accordion_icon", "floating_icon", "unknown_icon", "h_tiles_text", "v_tiles_text",
      "h_accordion_text", "v_accordion_text", "floating_text", "unknown_text",
    ],
    "builtins.cpu": [
      "enabled", "position", "order", "style", "content",
    ],
    "builtins.groups.system": ["position", "order", "style"],
    "builtins.groups": ["system"],
    "builtins.groups.system.style": [
      "background_color", "border_color", "border_width", "corner_radius", "margin_x", "margin_y",
      "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.cpu.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.cpu.content": [
      "label", "history_size", "line_width", "color", "sample_interval_seconds",
    ],
    "builtins.battery": [
      "enabled", "position", "order", "group", "style", "content", "colors", "tooltip",
    ],
    "builtins.battery.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.battery.content": [
      "unavailable_text", "icon_size", "color_mode", "fixed_color", "display_mode",
    ],
    "builtins.battery.colors": [
      "high", "medium", "low", "critical", "frame", "overlay_outline", "charging_overlay",
      "external_power_overlay", "on_hold_overlay", "unavailable",
    ],
    "builtins.battery.tooltip": [
      "text_color", "background_color", "border_color", "border_width", "corner_radius", "padding_x",
      "padding_y", "margin_x", "margin_y",
    ],
    "builtins.wifi": [
      "enabled", "position", "order", "group", "style", "content", "inline", "fields", "popup",
    ],
    "builtins.wifi.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.wifi.content": [
      "mode", "surface", "inline_separator", "disconnected_text", "denied_text", "active_color",
      "inactive_color",
    ],
    "builtins.wifi.inline": ["text_color"],
    "builtins.wifi.fields": [
      "ssid", "ipv4_address", "ipv6_address", "bssid", "interface", "hardware_address", "power",
      "service_active", "rssi", "noise", "snr", "link_quality", "tx_rate", "channel", "channel_band",
      "channel_width", "security", "phy_mode", "interface_mode", "country_code", "roaming",
      "ssid_changed_at", "interface_changed_at",
    ],
    "builtins.wifi.popup": [
      "text_color", "background_color", "border_color", "border_width", "corner_radius", "padding_x",
      "padding_y", "margin_x", "margin_y",
    ],
    "builtins.volume": [
      "enabled", "position", "order", "style", "content", "slider",
    ],
    "builtins.volume.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.volume.content": [
      "muted_icon", "low_icon", "high_icon", "show_percentage", "min", "max", "step",
    ],
    "builtins.volume.slider": ["expand_to_slider_on_hover", "width"],
    "builtins.calendar": [
      "enabled", "position", "order", "popup_mode", "style", "anchor", "composer", "upcoming",
      "appointments", "birthdays", "filters", "month",
    ],
    "builtins.calendar.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.calendar.anchor": [
      "layout", "item_format", "top_format", "bottom_format", "line_spacing", "top_text_color",
      "bottom_text_color",
    ],
    "builtins.calendar.composer": [
      "create_title", "edit_title", "title_label", "location_label", "calendar_label", "start_label",
      "end_label", "all_day_label", "travel_time_label", "alert_label", "add_alert_label",
      "open_calendar_label", "cancel_label", "save_label", "update_label", "remove_label",
      "delete_confirmation_title", "delete_confirmation_message", "title_placeholder",
      "location_placeholder", "default_calendar_name", "default_alert", "default_travel_time",
      "style", "alert_labels", "travel_time_labels",
    ],
    "builtins.calendar.composer.style": [
      "background_color", "border_color", "border_width", "corner_radius", "padding_x", "padding_y",
      "header_text_color",
    ],
    "builtins.calendar.composer.alert_labels": [
      "none", "at_time", "5_minutes", "10_minutes", "15_minutes", "30_minutes", "1_hour", "1_day",
      "custom",
    ],
    "builtins.calendar.composer.travel_time_labels": [
      "none", "5_minutes", "10_minutes", "15_minutes", "20_minutes", "30_minutes", "45_minutes",
      "1_hour", "90_minutes", "2_hours", "custom",
    ],
    "builtins.calendar.upcoming.events": ["days", "exclude_past_events"],
    "builtins.calendar.upcoming": ["events", "popup"],
    "builtins.calendar.upcoming.popup": [
      "background_color", "border_color", "border_width", "corner_radius", "padding_x", "padding_y",
      "margin_x", "margin_y", "spacing",
    ],
    "builtins.calendar.appointments": [
      "item_indent", "event_text_color", "empty_text_color", "secondary_text_color",
      "travel_text_color", "empty_text", "show_calendar_name", "show_all_day_label",
      "show_holiday_all_day_label", "all_day_label", "show_location", "location_icon",
      "location_icon_color", "show_travel_time", "show_end_time", "travel_icon", "travel_icon_color",
      "show_alert_icon", "alert_icon", "alert_icon_color",
    ],
    "builtins.calendar.birthdays": [
      "show_birthdays", "birthdays_show_age", "birthday_icon", "birthday_icon_color",
    ],
    "builtins.calendar.filters": [
      "included_calendar_names", "excluded_calendar_names", "included_calendar_ids",
      "excluded_calendar_ids", "included_calendar_source_ids", "excluded_calendar_source_ids",
    ],
    "builtins.calendar.month.popup.style": [
      "background_color", "border_color", "border_width", "corner_radius", "padding_x", "padding_y",
      "spacing", "margin_x", "margin_y",
    ],
    "builtins.calendar.month": ["popup"],
    "builtins.calendar.month.popup": [
      "style", "calendar", "selection", "agenda", "anchor", "today_button",
    ],
    "builtins.calendar.month.popup.calendar": [
      "show_week_numbers", "show_event_indicators", "header_text_color", "weekday_text_color",
      "first_weekday", "weekday_format", "weekday_symbols", "day_text_color",
      "outside_month_text_color", "today_cell_background_color", "today_cell_border_color",
      "today_cell_border_width", "indicator_color",
    ],
    "builtins.calendar.month.popup.selection": [
      "selected_text_color", "selected_background_color", "selection_date_format",
      "selection_date_separator", "allows_range_selection", "reset_selection_on_third_tap",
    ],
    "builtins.calendar.month.popup.agenda": [
      "layout", "appointments_scrollable", "appointments_min_height", "appointments_max_height",
      "agenda_title", "max_visible_appointments",
    ],
    "builtins.calendar.month.popup.anchor": ["date_format", "text_color", "show_date_text"],
    "builtins.calendar.month.popup.today_button": [
      "title", "border_color", "border_width", "icon",
    ],
    "builtins.time": [
      "enabled", "position", "order", "style", "content",
    ],
    "builtins.time.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.time.content": ["format"],
    "builtins.date": [
      "enabled", "position", "order", "style", "content",
    ],
    "builtins.date.style": [
      "icon", "text_color", "background_color", "border_color", "border_width", "corner_radius",
      "margin_x", "margin_y", "padding_x", "padding_y", "spacing", "opacity",
    ],
    "builtins.date.content": ["format"],
    "theme.colors": themeColorKeys,
  ]

  private static let freeFormSections: Set<String> = [
    "app.env",
    "builtins.calendar.composer.alert_labels",
    "builtins.calendar.composer.travel_time_labels",
  ]

  static func isFreeFormSection(_ path: String) -> Bool {
    freeFormSections.contains(path)
  }

  static func knownKeys(for path: String) -> Set<String> {
    if isBuiltinGroup(path) {
      return placementKeys.union(["style"])
    }

    if isBuiltinGroupStyle(path) {
      return widgetStyleKeys
    }

    return knownKeysBySection[path] ?? []
  }

  static func isKnownSection(_ path: String) -> Bool {
    knownKeysBySection[path] != nil
      || freeFormSections.contains(path)
      || isBuiltinGroup(path)
      || isBuiltinGroupStyle(path)
  }

  private static func isBuiltinGroup(_ path: String) -> Bool {
    let components = path.split(separator: ".")
    return components.count == 3
      && components[0] == "builtins"
      && components[1] == "groups"
  }

  private static func isBuiltinGroupStyle(_ path: String) -> Bool {
    let components = path.split(separator: ".")
    return components.count == 4
      && components[0] == "builtins"
      && components[1] == "groups"
      && components[3] == "style"
  }
}
