---@alias EasyBarEventName
---| '"interval"'
---| '"forced"'
---| '"system_woke"'
---| '"sleep"'
---| '"space_change"'
---| '"app_switch"'
---| '"display_change"'
---| '"power_source_change"'
---| '"charging_state_change"'
---| '"wifi_change"'
---| '"network_change"'
---| '"volume_change"'
---| '"mute_change"'
---| '"minute_tick"'
---| '"second_tick"'
---| '"calendar_change"'
---| '"focus_change"'
---| '"workspace_change"'
---| '"space_mode_change"'
---| '"mouse.entered"'
---| '"mouse.exited"'
---| '"mouse.clicked"'
---| '"mouse.down"'
---| '"mouse.up"'
---| '"mouse.scrolled"'
---| '"slider.preview"'
---| '"slider.changed"'

---@class EasyBarNetworkEventData
---@field primary_interface_is_tunnel? boolean Whether the current primary network interface is a tunnel.
---@field interface_name? string The network interface name when provided.

---@class EasyBarPowerEventData
---@field charging? boolean Whether the current power source is charging.

---@class EasyBarAudioEventData
---@field muted? boolean Whether the current audio output is muted.
---@field value? number The current audio-related value when provided.

---@class EasyBarEvent
---@field name string The dispatched event name.
---@field widget_id? string The subscribed widget id receiving the event.
---@field target_widget_id? string The concrete node id that received the interaction.
---@field app_name? string The focused app name for app-switch style events.
---@field button? EasyBarMouseButton|string The mouse button name, usually `left`, `right`, or `middle`.
---@field direction? EasyBarScrollDirection|string The scroll direction, usually `up`, `down`, `left`, or `right`.
---@field value? number|string|boolean The event value for slider and driver updates.
---@field delta_x? number Horizontal scroll delta.
---@field delta_y? number Vertical scroll delta.
---@field network? EasyBarNetworkEventData Structured network event data.
---@field power? EasyBarPowerEventData Structured power event data.
---@field audio? EasyBarAudioEventData Structured audio event data.

---@alias EasyBarEventHandler fun(event: EasyBarEvent)

---@class EasyBarEventToken
---@field name EasyBarEventName The canonical runtime event name sent by EasyBar.

---@class EasyBarMouseButtons
---@field left EasyBarMouseButton
---@field right EasyBarMouseButton
---@field middle EasyBarMouseButton

---@class EasyBarScrollDirections
---@field up EasyBarScrollDirection
---@field down EasyBarScrollDirection
---@field left EasyBarScrollDirection
---@field right EasyBarScrollDirection

---@class EasyBarMouseEvents
---@field entered? EasyBarEventToken Fired when the pointer enters the subscribed node frame.
---@field exited? EasyBarEventToken Fired when the pointer leaves the subscribed node frame.
---@field clicked? EasyBarEventToken Fired when the subscribed node is clicked.
---@field down? EasyBarEventToken Fired on mouse button press over the subscribed node.
---@field up? EasyBarEventToken Fired on mouse button release over the subscribed node.
---@field scrolled? EasyBarEventToken Fired when the pointer scrolls over the subscribed node.
---@field left_button EasyBarMouseButton Constant for `event.button == "left"`.
---@field right_button EasyBarMouseButton Constant for `event.button == "right"`.
---@field middle_button EasyBarMouseButton Constant for `event.button == "middle"`.
---@field up_scroll EasyBarScrollDirection Constant for `event.direction == "up"`.
---@field down_scroll EasyBarScrollDirection Constant for `event.direction == "down"`.
---@field left_scroll EasyBarScrollDirection Constant for `event.direction == "left"`.
---@field right_scroll EasyBarScrollDirection Constant for `event.direction == "right"`.
---@field buttons EasyBarMouseButtons Nested mouse-button constants.
---@field directions EasyBarScrollDirections Nested scroll-direction constants.

---@class EasyBarSliderEvents
---@field preview? EasyBarEventToken Fired while a slider is being previewed or dragged.
---@field changed? EasyBarEventToken Fired when a slider value is committed.

---@class EasyBarEvents
---@field forced? EasyBarEventToken Fired when EasyBar or `easybar` triggers a manual refresh.
---@field system_woke? EasyBarEventToken Fired after the system wakes from sleep.
---@field sleep? EasyBarEventToken Fired before the system goes to sleep.
---@field space_change? EasyBarEventToken Fired when the active macOS space changes.
---@field app_switch? EasyBarEventToken Fired when the frontmost app changes.
---@field display_change? EasyBarEventToken Fired when attached displays change.
---@field power_source_change? EasyBarEventToken Fired when the power source changes.
---@field charging_state_change? EasyBarEventToken Fired when charging starts or stops.
---@field wifi_change? EasyBarEventToken Fired when Wi-Fi state or SSID changes.
---@field network_change? EasyBarEventToken Fired when network routing or tunnel state changes.
---@field volume_change? EasyBarEventToken Fired when output volume changes.
---@field mute_change? EasyBarEventToken Fired when mute state changes.
---@field minute_tick? EasyBarEventToken Fired once per minute.
---@field second_tick? EasyBarEventToken Fired once per second.
---@field calendar_change? EasyBarEventToken Fired when the calendar snapshot updates.
---@field focus_change? EasyBarEventToken Fired when workspace focus changes.
---@field workspace_change? EasyBarEventToken Fired when workspace layout or selection changes.
---@field space_mode_change? EasyBarEventToken Fired when the AeroSpace layout mode changes.
---@field mouse? EasyBarMouseEvents Mouse interaction event tokens and constants.
---@field slider? EasyBarSliderEvents Slider interaction event tokens.
