import Darwin
import EasyBarShared
import Foundation

/// Prints user-facing CLI output.
enum CLIOutput {
  /// Prints an error.
  static func printError(_ message: String) {
    fputs("easybar: \(message)\n", stderr)
  }

  /// Prints a warning.
  static func printWarning(_ message: String) {
    fputs("easybar: warning: \(message)\n", stderr)
  }

  /// Prints the version.
  static func printVersion() {
    fputs("easybar \(BuildInfo.appVersion)\n", stdout)
  }

  /// Prints usage.
  static func printUsage() {
    let commandLines = CLI.cmdOptions.map {
      CLI.formatOption(CLI.optionText(for: $0), $0.description)
    }
    let appOptionLines = CLI.appOptions.map {
      CLI.formatOption(CLI.optionText(for: $0), $0.description)
    }

    let lines: [String] =
      [
        "usage:",
        "  easybar <command> [options]",
        "",
        "commands:",
        CLI.formatOption("logs", "Show retained logs and follow new entries"),
        CLI.formatOption("inbox send", "Add or update a native inbox message"),
        CLI.formatOption("inbox read", "Print native inbox messages"),
        CLI.formatOption("inbox mark-read", "Mark matching messages as read"),
        CLI.formatOption("inbox mark-unread", "Mark matching messages as unread"),
        CLI.formatOption("inbox dismiss", "Dismiss matching messages"),
        CLI.formatOption("inbox remove", "Delete one message by source and ID"),
        CLI.formatOption("inbox clear", "Remove one source or all inbox messages"),
      ] + commandLines + [
        "",
        "inbox options:",
        CLI.formatOption("--source <name>", "Publisher source (required by send and mutations)"),
        CLI.formatOption("--id <id>", "Stable message identifier; generated by send when omitted"),
        CLI.formatOption("--title <text>", "Message title required by inbox send"),
        CLI.formatOption("--message <text>", "Optional message body"),
        CLI.formatOption("--severity <level>", "info, success, warning, or error"),
        CLI.formatOption("--group <name>", "Optional inbox category/group"),
        CLI.formatOption("--url <url>", "Optional HTTP(S) URL opened by the message action"),
        CLI.formatOption("--read", "Create a message in the read state"),
        CLI.formatOption("--unread", "Read only unread messages"),
        CLI.formatOption("--json", "Print inbox read results as JSON"),
        CLI.formatOption("--all", "Allow inbox clear to remove every source"),
        "",
        "log options:",
      ]
      + CLI.logOptions.map {
        CLI.formatOption(CLI.optionText(for: $0), $0.description)
      } + [
        "",
        "options:",
      ] + appOptionLines

    fputs(lines.joined(separator: "\n") + "\n", stderr)
  }

  /// Prints one metrics snapshot.
  static func printMetricsSnapshot(_ snapshot: IPC.MetricsSnapshot) {
    fputs(MetricsRenderer.snapshotText(snapshot) + "\n", stdout)
  }

  /// Prints inbox items as readable records or a JSON array.
  static func printInboxItems(_ items: [IPC.InboxItem], json: Bool) throws {
    if json {
      let encoder = JSONEncoder()
      encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
      let data = try encoder.encode(items)
      guard let output = String(data: data, encoding: .utf8) else {
        throw AppError.message("failed to encode inbox output")
      }
      fputs(output + "\n", stdout)
      return
    }

    if items.isEmpty {
      fputs("No inbox messages.\n", stdout)
      return
    }

    for item in items {
      let state = item.unread ? "unread" : "read"
      fputs("[\(item.severity.rawValue)] \(item.source)/\(item.id) (\(state))\n", stdout)
      fputs("  \(item.title)\n", stdout)
      if let message = item.message, !message.isEmpty { fputs("  \(message)\n", stdout) }
      if let group = item.group, !group.isEmpty { fputs("  group: \(group)\n", stdout) }
      if let url = item.url, !url.isEmpty { fputs("  url: \(url)\n", stdout) }
    }
  }
}
