import Foundation
import PackagePlugin

private enum BuildInfoPluginError: Error, CustomStringConvertible {
  case unreadableVersionFile(Path, Error)
  case invalidVersion(String)

  var description: String {
    switch self {
    case .unreadableVersionFile(let path, let error):
      return "failed to read EasyBar build version from \(path): \(error)"
    case .invalidVersion(let version):
      return "invalid EasyBar build version: \(version)"
    }
  }
}

@main
struct EasyBarBuildInfoPlugin: BuildToolPlugin {
  private static let defaultVersion = "dev"
  private static let versionFileName = "easybar-build-version"

  func createBuildCommands(
    context: PluginContext,
    target _: Target
  ) throws -> [Command] {
    let output = context.pluginWorkDirectory.appending("BuildInfo.generated.swift")
    let versionFile = context.package.directory
      .appending(".build")
      .appending(Self.versionFileName)
    let version = try Self.readVersion(from: versionFile)

    guard Self.isValidVersion(version) else {
      throw BuildInfoPluginError.invalidVersion(version)
    }

    let script = """
      set -eu

      output="$1"
      version="$2"

      mkdir -p "$(dirname "$output")"
      {
        printf '%s\n' '// Generated by EasyBarBuildInfoPlugin. Do not edit.'
        printf '%s\n' 'public enum BuildInfo {'
        printf '  public static let appVersion = "%s"\n' "$version"
        printf '%s\n' '}'
        printf '\n'
      } > "$output"
      """

    return [
      .buildCommand(
        displayName: "Generate EasyBar build version \(version)",
        executable: Path("/bin/sh"),
        arguments: [
          "-c",
          script,
          "easybar-build-info",
          output.string,
          version,
        ],
        inputFiles: Self.inputFiles(for: versionFile),
        outputFiles: [output]
      )
    ]
  }

  private static func readVersion(from path: Path) throws -> String {
    guard FileManager.default.fileExists(atPath: path.string) else {
      return defaultVersion
    }

    do {
      return try String(contentsOfFile: path.string, encoding: .utf8)
        .trimmingCharacters(in: .whitespacesAndNewlines)
    } catch {
      throw BuildInfoPluginError.unreadableVersionFile(path, error)
    }
  }

  private static func inputFiles(for path: Path) -> [Path] {
    FileManager.default.fileExists(atPath: path.string) ? [path] : []
  }

  private static func isValidVersion(_ version: String) -> Bool {
    guard !version.isEmpty else { return false }

    return version.unicodeScalars.allSatisfy { scalar in
      switch scalar.value {
      case 43, 45, 46, 48...57, 65...90, 95, 97...122:
        return true
      default:
        return false
      }
    }
  }
}
