--- Module contract:
--- Owns generated EasyBar theme token names shared across Lua runtime modules.
--- Returns one table containing `keys` in stable public order.
-- This file is generated by scripts/generate_theme_tokens.py. Do not edit by hand.
--- Theme token module table.
local M = {}

--- Public theme token names exposed to Lua widgets and docs.
M.keys = {
	"background",
	"surface",
	"surface_elevated",
	"surface_hover",
	"text",
	"text_secondary",
	"text_tertiary",
	"muted",
	"muted_secondary",
	"outside_month",
	"accent",
	"accent_secondary",
	"accent_soft",
	"success",
	"success_secondary",
	"warning",
	"orange",
	"error",
	"danger",
	"border",
	"border_strong",
	"border_subtle",
	"selection_text",
	"selection_background",
	"transparent",
	"overlay_outline",
	"overlay_text",
	"today_button_border",
}

return M
