import EasyBarShared

typealias NativeMonthCalendarPopupSection = EasyBarShared.CalendarAgentSection
typealias NativeMonthCalendarPopupItem = EasyBarShared.CalendarAgentItem
typealias NativeMonthCalendarEvent = EasyBarShared.CalendarAgentEvent
