import EasyBarShared

typealias NativeMonthCalendarPopupSection = CalendarAgentSection
typealias NativeMonthCalendarPopupItem = CalendarAgentItem
typealias NativeMonthCalendarEvent = CalendarAgentEvent
