extension ConfigSchemaRegistry {
  static let systemLines: [Line] = [
    section(name: "builtins.inbox"),
    entry(key: "enabled", value: "true", description: "Shows or hides the native shared inbox."),
    entry(
      key: "position", value: "\"right\"",
      description: "Places the inbox on the left, center, or right side of the bar."),
    entry(key: "order", value: "5", description: "Sort order among widgets in the same position."),
    .blank,
    section(name: "builtins.inbox.style"),
    entry(key: "unread_icon", value: "\"􀛬\"", description: "Icon shown when unread inbox messages exist."),
    entry(key: "read_icon", value: "\"􀍕\"", description: "Icon shown when no unread inbox messages exist."),
    entry(
      key: "unread_icon_color", value: "\"theme.text_secondary\"",
      description: "Color of the inbox icon when unread messages exist."),
    entry(
      key: "read_icon_color", value: "\"theme.muted\"",
      description: "Color of the inbox icon when no unread messages exist."),
    entry(key: "unread_count_color", value: "\"theme.accent\"", description: "Color of the unread count."),
    entry(
      key: "background_color", value: "\"theme.transparent\"", description: "Background color of the inbox anchor."),
    entry(key: "border_color", value: "\"theme.transparent\"", description: "Border color of the inbox anchor."),
    entry(key: "border_width", value: "0", description: "Border width of the inbox anchor."),
    entry(key: "corner_radius", value: "8", description: "Corner radius of the inbox anchor."),
    entry(key: "margin_x", value: "0", description: "Horizontal outer margin around the inbox anchor."),
    entry(key: "margin_y", value: "0", description: "Vertical outer margin around the inbox anchor."),
    entry(key: "padding_x", value: "7", description: "Horizontal inner padding of the inbox anchor."),
    entry(key: "padding_y", value: "3", description: "Vertical inner padding of the inbox anchor."),
    entry(key: "spacing", value: "4", description: "Gap between the inbox icon and unread count."),
    entry(key: "opacity", value: "1", description: "Overall opacity of the inbox anchor."),
    .blank,
    section(name: "builtins.inbox.colors"),
    entry(key: "background", value: "\"theme.background\"", description: "Background color of the inbox popup."),
    entry(key: "border", value: "\"theme.border_strong\"", description: "Border color of the inbox popup."),
    entry(key: "title", value: "\"theme.text\"", description: "Color of titles in the inbox popup."),
    entry(key: "text", value: "\"theme.text_secondary\"", description: "Color of message body text."),
    entry(key: "muted", value: "\"theme.muted\"", description: "Color of secondary labels and empty text."),
    entry(
      key: "item_background", value: "\"theme.surface\"", description: "Background color of individual messages."),
    entry(key: "action", value: "\"theme.accent\"", description: "Color of message action buttons."),
    entry(key: "info", value: "\"theme.accent\"", description: "Unread indicator color for info messages."),
    entry(key: "success", value: "\"theme.success\"", description: "Unread indicator color for success messages."),
    entry(key: "warning", value: "\"theme.warning\"", description: "Unread indicator color for warning messages."),
    entry(key: "error", value: "\"theme.error\"", description: "Unread indicator color for error messages."),
    .blank,
    section(name: "builtins.inbox.content"),
    entry(
      key: "group_by", value: "\"source\"", description: "Groups messages by source, date, category, severity, or none."
    ),
    entry(
      key: "sort_by", value: "\"timestamp\"", description: "Sorts messages by timestamp, source, severity, or title."),
    entry(key: "sort_descending", value: "true", description: "Reverses the configured sort order when true."),
    entry(
      key: "show_unread_count", value: "true", description: "Shows the total unread message count beside the icon."),
    entry(
      key: "use_inactive_style_when_read", value: "true",
      description: "Uses the read icon and color when no unread messages remain."),
    entry(
      key: "show_when_empty", value: "true",
      description: "Keeps the read-state inbox icon visible when no messages exist."
    ),
    entry(
      key: "show_source_actions", value: "true",
      description: "Shows publisher-provided actions in the inbox popup header."),
    entry(
      key: "popup_width", value: "360", description: "Sets the inbox popup width in points (240–800)."),
    entry(
      key: "popup_max_height", value: "540",
      description: "Sets the maximum scrollable message-list height in points (120–1000)."),
    entry(
      key: "max_items", value: "100", description: "Maximum number of current messages accepted from each publisher."),
    .blank,
    section(name: "builtins.cpu"),
    entry(
      key: "enabled",
      value: "false",
      description: "Shows or hides the CPU widget.",
    ),
    entry(
      key: "position",
      value: "\"right\"",
      description: "Places the widget on the left, center, or right side of the bar.",
    ),
    entry(
      key: "order",
      value: "10",
      description: "Sort order among widgets in the same position.",
    ),
    .blank,
    .comment("# Example native group configuration. This is disabled by default."),
    .comment("# Uncomment this block and the `group = \"system\"` lines below if you want"),
    .comment("# battery and Wi-Fi to be rendered inside one shared native container."),
    .blank,
    section(
      name: "builtins.groups.system",
      commented: true,
      prefix: "#",
      documented: false,
    ),
    entry(
      key: "position",
      value: "\"right\"",
      description: "Places the native group on the left, center, or right side of the bar.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "order",
      value: "40",
      description: "Sort order among widgets in the same position.",
      commented: true,
      prefix: "#",
    ),
    .blank,
    section(
      name: "builtins.groups.system.style",
      commented: true,
      prefix: "#",
      documented: false,
    ),
    entry(
      key: "background_color",
      value: "\"theme.surface\"",
      description: "Background color of the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "border_color",
      value: "\"theme.border\"",
      description: "Border color of the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "border_width",
      value: "1",
      description: "Border width of the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "corner_radius",
      value: "8",
      description: "Corner radius of the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "margin_y",
      value: "0",
      description: "Vertical outer margin around the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "padding_x",
      value: "8",
      description: "Horizontal inner padding around the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "padding_y",
      value: "2",
      description: "Vertical inner padding around the native group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "spacing",
      value: "6",
      description: "Gap between native child widgets in the group.",
      commented: true,
      prefix: "#",
    ),
    entry(
      key: "opacity",
      value: "1",
      description: "Overall opacity of the native group.",
      commented: true,
      prefix: "#",
    ),
    .blank,
    section(name: "builtins.cpu.style"),
    entry(
      key: "icon",
      value: "\"󰍛\"",
      description: "Leading icon of the widget.",
    ),
    entry(
      key: "text_color",
      value: "\"theme.text\"",
      description: "Text color of the widget when no content color is set.",
    ),
    entry(
      key: "background_color",
      value: "\"theme.transparent\"",
      description: "Background color of the widget.",
    ),
    entry(
      key: "border_color",
      value: "\"theme.transparent\"",
      description: "Border color of the widget.",
    ),
    entry(
      key: "border_width",
      value: "0",
      description: "Border width of the widget.",
    ),
    entry(
      key: "corner_radius",
      value: "0",
      description: "Corner radius of the widget background.",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the widget.",
    ),
    entry(
      key: "margin_y",
      value: "0",
      description: "Vertical outer margin around the widget.",
    ),
    entry(
      key: "padding_x",
      value: "8",
      description: "Horizontal inner padding of the widget.",
    ),
    entry(
      key: "padding_y",
      value: "4",
      description: "Vertical inner padding of the widget.",
    ),
    entry(
      key: "spacing",
      value: "6",
      description: "Gap between the icon, label, and sparkline.",
    ),
    entry(
      key: "opacity",
      value: "1",
      description: "Overall opacity of the widget.",
    ),
    .blank,
    section(name: "builtins.cpu.content"),
    entry(
      key: "label",
      value: "\"CPU\"",
      description: "Text label shown next to the sparkline.",
    ),
    entry(
      key: "history_size",
      value: "10",
      description: "Number of samples kept in the sparkline history.",
    ),
    entry(
      key: "line_width",
      value: "1.8",
      description: "Stroke width of the sparkline line.",
    ),
    entry(
      key: "color",
      value: "\"theme.success_secondary\"",
      description: "Color of the sparkline and label.",
    ),
    entry(
      key: "sample_interval_seconds",
      value: "1",
      description: "Polling interval in seconds.",
    ),
    .blank,
    section(name: "builtins.battery"),
    entry(
      key: "enabled",
      value: "true",
      description: "Shows or hides the battery widget.",
    ),
    entry(
      key: "position",
      value: "\"right\"",
      description: "Places the widget on the left, center, or right side of the bar.",
    ),
    entry(
      key: "order",
      value: "20",
      description: "Sort order among widgets in the same position.",
    ),
    entry(
      key: "group",
      value: "\"system\"",
      description: "Optional native group id that should contain this widget.",
      commented: true,
      prefix: "# ",
    ),
    .blank,
    section(name: "builtins.battery.style"),
    entry(
      key: "icon",
      value: "\"􀫯\"",
      description: "Fallback or default battery icon.",
    ),
    entry(
      key: "text_color",
      value: "\"theme.text\"",
      description: "Used when color_mode is fixed or data is unavailable.",
    ),
    entry(
      key: "background_color",
      value: "\"theme.transparent\"",
      description: "Background color of the widget.",
    ),
    entry(
      key: "border_color",
      value: "\"theme.transparent\"",
      description: "Border color of the widget.",
    ),
    entry(
      key: "border_width",
      value: "0",
      description: "Border width of the widget.",
    ),
    entry(
      key: "corner_radius",
      value: "8",
      description: "Corner radius of the widget background.",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the widget.",
    ),
    entry(
      key: "margin_y",
      value: "0",
      description: "Vertical outer margin around the widget.",
    ),
    entry(
      key: "padding_x",
      value: "4",
      description: "Horizontal inner padding of the widget.",
    ),
    entry(
      key: "padding_y",
      value: "0",
      description: "Vertical inner padding of the widget.",
    ),
    entry(
      key: "spacing",
      value: "6",
      description: "Gap between the battery icon and text.",
    ),
    entry(
      key: "opacity",
      value: "1.0",
      description: "Overall opacity of the widget.",
    ),
    .blank,
    section(name: "builtins.battery.content"),
    entry(
      key: "unavailable_text",
      value: "\"n/a\"",
      description: "Fallback text shown when battery data is unavailable.",
    ),
    entry(
      key: "icon_size",
      value: "18",
      description: "Font size of the battery icon.",
    ),
    entry(
      key: "color_mode",
      value: "\"fixed\"",
      description: "Battery color mode: dynamic | fixed.",
    ),
    entry(
      key: "fixed_color",
      value: "\"theme.text\"",
      description: "Color used only when color_mode = \"fixed\".",
    ),
    entry(
      key: "display_mode",
      value: "\"expand\"",
      description: "Display mode: none | tooltip | expand | always.",
    ),
    .blank,
    section(name: "builtins.battery.colors"),
    entry(
      key: "high",
      value: "\"theme.success\"",
      description: "Color used for 70-100%.",
    ),
    entry(
      key: "medium",
      value: "\"theme.warning\"",
      description: "Color used for 50-69%.",
    ),
    entry(
      key: "low",
      value: "\"theme.orange\"",
      description: "Color used for 30-49%.",
    ),
    entry(
      key: "critical",
      value: "\"theme.danger\"",
      description: "Color used for 0-29%.",
    ),
    entry(
      key: "frame",
      value: "\"theme.muted\"",
      description: "Secondary palette color for the battery frame.",
    ),
    entry(
      key: "overlay_outline",
      value: "\"theme.overlay_outline\"",
      description: "Outline color drawn behind battery overlay symbols.",
    ),
    entry(
      key: "charging_overlay",
      value: "\"theme.overlay_text\"",
      description: "Color of the charging bolt overlay.",
    ),
    entry(
      key: "external_power_overlay",
      value: "\"theme.overlay_text\"",
      description: "Color of the plugged-in holding overlay.",
    ),
    entry(
      key: "on_hold_overlay",
      value: "\"theme.overlay_text\"",
      description: "Color of the on-hold pause overlay.",
    ),
    entry(
      key: "unavailable",
      value: "\"theme.muted\"",
      description: "Color used when battery data is unavailable.",
    ),
    .blank,
    section(name: "builtins.battery.tooltip"),
    entry(
      key: "text_color",
      value: "\"theme.text\"",
      description: "Text color used in the tooltip.",
    ),
    entry(
      key: "background_color",
      value: "\"theme.background\"",
      description: "Background color of the tooltip.",
    ),
    entry(
      key: "border_color",
      value: "\"theme.border_strong\"",
      description: "Border color of the tooltip.",
    ),
    entry(
      key: "border_width",
      value: "1",
      description: "Border width of the tooltip.",
    ),
    entry(
      key: "corner_radius",
      value: "8",
      description: "Corner radius of the tooltip.",
    ),
    entry(
      key: "padding_x",
      value: "8",
      description: "Horizontal inner padding of the tooltip.",
    ),
    entry(
      key: "padding_y",
      value: "6",
      description: "Vertical inner padding of the tooltip.",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the tooltip.",
    ),
    entry(
      key: "margin_y",
      value: "8",
      description: "Vertical outer margin around the tooltip.",
    ),
    .blank,
    section(name: "builtins.wifi"),
    entry(
      key: "enabled",
      value: "true",
      description: "Shows or hides the built-in Wi-Fi widget.",
    ),
    entry(
      key: "position",
      value: "\"right\"",
      description: "Places the widget on the left, center, or right side of the bar.",
    ),
    entry(
      key: "order",
      value: "30",
      description: "Sort order among widgets in the same position.",
    ),
    entry(
      key: "group",
      value: "\"system\"",
      description: "Optional native group id that should contain this widget.",
      commented: true,
      prefix: "# ",
    ),
    .blank,
    section(name: "builtins.wifi.style"),
    entry(
      key: "background_color",
      value: "\"theme.transparent\"",
      description: "Background color of the widget.",
    ),
    entry(
      key: "border_color",
      value: "\"theme.transparent\"",
      description: "Border color of the widget.",
    ),
    entry(
      key: "border_width",
      value: "0",
      description: "Border width of the widget.",
    ),
    entry(
      key: "corner_radius",
      value: "8",
      description: "Corner radius of the widget.",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the widget.",
    ),
    entry(
      key: "margin_y",
      value: "0",
      description: "Vertical outer margin around the widget.",
    ),
    entry(
      key: "padding_x",
      value: "8",
      description: "Horizontal inner padding of the widget.",
    ),
    entry(
      key: "padding_y",
      value: "0",
      description: "Vertical inner padding of the widget.",
    ),
    entry(
      key: "spacing",
      value: "6",
      description: "Gap between the signal bars and optional inline label.",
    ),
    entry(
      key: "opacity",
      value: "1",
      description: "Overall opacity of the widget.",
    ),
    .blank,
    section(name: "builtins.wifi.content"),
    entry(
      key: "mode",
      value: "\"icon\"",
      description: "Content mode: icon | inline | details.",
    ),
    entry(
      key: "surface",
      value: "\"hover\"",
      description: "Visibility timing for inline/details content: always | hover.",
    ),
    entry(
      key: "inline_separator",
      value: "\" | \"",
      description: "Separator used between enabled field values when mode = \"inline\".",
    ),
    entry(
      key: "disconnected_text",
      value: "\"disconnected\"",
      description: "Text shown for SSID when Wi-Fi is not connected.",
    ),
    entry(
      key: "denied_text",
      value: "\"denied\"",
      description: "Text shown for SSID when Wi-Fi permission is unavailable.",
    ),
    entry(
      key: "active_color",
      value: "\"theme.text\"",
      description: "Color of active signal bars.",
    ),
    entry(
      key: "inactive_color",
      value: "\"theme.muted\"",
      description: "Color of inactive signal bars.",
    ),
    .blank,
    section(name: "builtins.wifi.inline"),
    entry(
      key: "text_color",
      value: "\"theme.text\"",
      description: "Text color used for inline content.",
    ),
    .blank,
    section(name: "builtins.wifi.fields"),
    entry(
      key: "ssid",
      value: "false",
      description: "Enables the current Wi-Fi SSID for inline and details modes.",
    ),
    entry(
      key: "ipv4_address",
      value: "false",
      description: "Enables the primary IPv4 address for inline and details modes.",
    ),
    entry(
      key: "ipv6_address",
      value: "false",
      description: "Enables the primary IPv6 address for inline and details modes.",
    ),
    entry(
      key: "bssid",
      value: "false",
      description: "Enables the current Wi-Fi BSSID for inline and details modes.",
    ),
    entry(
      key: "interface",
      value: "false",
      description: "Enables the current Wi-Fi interface name for inline and details modes.",
    ),
    entry(
      key: "hardware_address",
      value: "false",
      description: "Enables the current Wi-Fi hardware address for inline and details modes.",
    ),
    entry(
      key: "power",
      value: "false",
      description: "Enables the current Wi-Fi power state for inline and details modes.",
    ),
    entry(
      key: "service_active",
      value: "false",
      description: "Enables the CoreWLAN service state for inline and details modes.",
    ),
    entry(
      key: "rssi",
      value: "false",
      description: "Enables signal strength in dBm for inline and details modes.",
    ),
    entry(
      key: "noise",
      value: "false",
      description: "Enables the noise floor in dBm for inline and details modes.",
    ),
    entry(
      key: "snr",
      value: "false",
      description: "Enables the signal-to-noise ratio in dB for inline and details modes.",
    ),
    entry(
      key: "link_quality",
      value: "false",
      description: "Enables the derived link quality percentage for inline and details modes.",
    ),
    entry(
      key: "tx_rate",
      value: "false",
      description: "Enables the current transmit rate for inline and details modes.",
    ),
    entry(
      key: "channel",
      value: "false",
      description: "Enables the current Wi-Fi channel for inline and details modes.",
    ),
    entry(
      key: "channel_band",
      value: "false",
      description: "Enables the current Wi-Fi band for inline and details modes.",
    ),
    entry(
      key: "channel_width",
      value: "false",
      description: "Enables the current Wi-Fi channel width for inline and details modes.",
    ),
    entry(
      key: "security",
      value: "false",
      description: "Enables the current Wi-Fi security mode for inline and details modes.",
    ),
    entry(
      key: "phy_mode",
      value: "false",
      description: "Enables the current Wi-Fi PHY mode for inline and details modes.",
    ),
    entry(
      key: "interface_mode",
      value: "false",
      description: "Enables the current Wi-Fi interface mode for inline and details modes.",
    ),
    entry(
      key: "country_code",
      value: "false",
      description: "Enables the current Wi-Fi country code for inline and details modes.",
    ),
    entry(
      key: "roaming",
      value: "false",
      description:
        "Enables whether access-point roaming was detected for inline and details modes.",
    ),
    entry(
      key: "ssid_changed_at",
      value: "false",
      description: "Enables the last SSID change timestamp for inline and details modes.",
    ),
    entry(
      key: "interface_changed_at",
      value: "false",
      description: "Enables the last interface change timestamp for inline and details modes.",
    ),
    .blank,
    section(name: "builtins.wifi.popup"),
    entry(
      key: "text_color",
      value: "\"theme.text\"",
      description: "Text color used in the Wi-Fi popup.",
    ),
    entry(
      key: "background_color",
      value: "\"theme.background\"",
      description: "Background color of the Wi-Fi popup.",
    ),
    entry(
      key: "border_color",
      value: "\"theme.border_strong\"",
      description: "Border color of the Wi-Fi popup.",
    ),
    entry(
      key: "border_width",
      value: "1",
      description: "Border width of the Wi-Fi popup.",
    ),
    entry(
      key: "corner_radius",
      value: "8",
      description: "Corner radius of the Wi-Fi popup.",
    ),
    entry(
      key: "padding_x",
      value: "8",
      description: "Horizontal inner padding of the Wi-Fi popup.",
    ),
    entry(
      key: "padding_y",
      value: "6",
      description: "Vertical inner padding of the Wi-Fi popup.",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the Wi-Fi popup.",
    ),
    entry(
      key: "margin_y",
      value: "8",
      description: "Vertical outer margin around the Wi-Fi popup.",
    ),
    .blank,
    section(name: "builtins.volume"),
    entry(
      key: "enabled",
      value: "false",
      description: "Shows or hides the volume widget.",
    ),
    entry(
      key: "position",
      value: "\"right\"",
      description: "Places the widget on the left, center, or right side of the bar.",
    ),
    entry(
      key: "order",
      value: "20",
      description: "Sort order among widgets in the same position.",
    ),
    .blank,
    section(name: "builtins.volume.style"),
    entry(
      key: "text_color",
      value: "\"theme.text\"",
      description: "Text color of the widget.",
    ),
    entry(
      key: "background_color",
      value: "\"theme.transparent\"",
      description: "Background color of the widget.",
    ),
    entry(
      key: "border_color",
      value: "\"theme.transparent\"",
      description: "Border color of the widget.",
    ),
    entry(
      key: "border_width",
      value: "0",
      description: "Border width of the widget.",
    ),
    entry(
      key: "corner_radius",
      value: "8",
      description: "Corner radius of the widget background.",
    ),
    entry(
      key: "margin_x",
      value: "0",
      description: "Horizontal outer margin around the widget.",
    ),
    entry(
      key: "margin_y",
      value: "0",
      description: "Vertical outer margin around the widget.",
    ),
    entry(
      key: "padding_x",
      value: "8",
      description: "Horizontal inner padding of the widget.",
    ),
    entry(
      key: "padding_y",
      value: "0",
      description: "Vertical inner padding of the widget.",
    ),
    entry(
      key: "spacing",
      value: "8",
      description: "Gap between the icon, label, and slider.",
    ),
    entry(
      key: "opacity",
      value: "1.0",
      description: "Overall opacity of the widget.",
    ),
    .blank,
    section(name: "builtins.volume.content"),
    entry(
      key: "muted_icon",
      value: "\"􀊢\"",
      description: "Icon shown when audio is muted.",
    ),
    entry(
      key: "low_icon",
      value: "\"􀊤\"",
      description: "Icon shown for low volume.",
    ),
    entry(
      key: "high_icon",
      value: "\"􀊦\"",
      description: "Icon shown for high volume.",
    ),
    entry(
      key: "show_percentage",
      value: "true",
      description: "Shows the volume percentage text.",
    ),
    entry(
      key: "min",
      value: "0",
      description: "Minimum slider and display value.",
    ),
    entry(
      key: "max",
      value: "100",
      description: "Maximum slider and display value.",
    ),
    entry(
      key: "step",
      value: "1",
      description: "Slider step size.",
    ),
    .blank,
    section(name: "builtins.volume.slider"),
    entry(
      key: "expand_to_slider_on_hover",
      value: "true",
      description: "Expands from compact mode to slider mode on hover.",
    ),
    entry(
      key: "width",
      value: "80",
      description: "Width of the slider when shown.",
    ),
    .blank,
  ]
}
