import Foundation

/// User-facing config schema metadata used by generators and typo warnings.
///
/// Keep this close to the parsed config types so default config examples,
/// configuration reference docs, and unknown-key warnings share one source.
public enum ConfigSchemaRegistry {
  /// One line in the generated default config file.
  public enum Line: Sendable {
    case blank
    case comment(String)
    case section(name: String, commented: Bool, prefix: String)
    case entry(key: String, value: String, description: String, commented: Bool, prefix: String)
  }

  /// Default config file lines in stable user-facing order.
  public static let lines: [Line] = [
    .section(
      name: #"app"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"widgets_dir"#,
      value: #""~/.config/easybar/widgets""#,
      description: #"Directory that contains your custom Lua widget files."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"lua_path"#,
      value: #""lua""#,
      description: #"Path to the Lua executable EasyBar uses for scripted widgets."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"lua_socket_path"#,
      value: #""$EASYBAR_RUNTIME_DIR/lua-runtime.sock""#,
      description:
        #"Unix socket path used by EasyBar and the Lua widget runtime transport. $EASYBAR_RUNTIME_DIR expands to EasyBar's user-scoped temporary runtime directory."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"watch_config"#,
      value: #"true"#,
      description: #"Reloads EasyBar automatically when config.toml changes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"lock_dir"#,
      value: #""$EASYBAR_RUNTIME_DIR""#,
      description: #"Directory that contains lock files used by EasyBar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"widget_editor_stub_path"#,
      value: #""~/.local/share/easybar/easybar_api.lua""#,
      description: #"LuaLS/editor stub path EasyBar keeps in sync for widget authoring."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"develop"#,
      value: #"false"#,
      description: #"Shows the developer menu section without holding Shift when right-clicking the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"app.env"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"PATH"#,
      value: #""/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin""#,
      description: #"Environment overrides passed into the Lua runtime and widget shell commands."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"app.lua_commands"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"timeout_seconds"#,
      value: #"5"#,
      description: #"Default hard timeout for easybar.exec and easybar.exec_async commands."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"max_output_bytes"#,
      value: #"65536"#,
      description: #"Default combined stdout and stderr capture limit for one command."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"max_async_jobs"#,
      value: #"8"#,
      description: #"Maximum concurrent easybar.exec_async jobs before new jobs are rejected."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"theme"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"name"#,
      value: #""default""#,
      description: #"Name of the default theme. Must match a theme file name without the .toml extension."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"themes_dir"#,
      value: #""~/.config/easybar/themes""#,
      description: #"Directory that contains your custom theme files."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"logging"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Mirrors stdout and stderr into per-process log files when true."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"level"#,
      value: #""info""#,
      description: #"Minimum log level: trace | debug | info | warn | error."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"directory"#,
      value: #""~/.local/state/easybar""#,
      description: #"Directory where EasyBar writes easybar.out, calendar-agent.out, and network-agent.out."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"agents.calendar"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"true"#,
      description: #"Starts the calendar socket client in EasyBar and enables the calendar helper contract."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"socket_path"#,
      value: #""$EASYBAR_RUNTIME_DIR/calendar-agent.sock""#,
      description: #"Unix socket path used by EasyBar and the calendar agent."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"agents.network"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"true"#,
      description: #"Starts the network socket client in EasyBar and enables the Wi-Fi helper contract."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"socket_path"#,
      value: #""$EASYBAR_RUNTIME_DIR/network-agent.sock""#,
      description: #"Unix socket path used by EasyBar and the network agent."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"refresh_interval_seconds"#,
      value: #"60"#,
      description: #"Fallback polling interval for Wi-Fi state. Set to 0 to disable polling."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"allow_unauthorized_non_sensitive_fields"#,
      value: #"false"#,
      description:
        #"When false, Wi-Fi field requests fail while location permission is denied. When true, only non-sensitive non-Wi-Fi fields may still be returned."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"bar"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"height"#,
      value: #"32"#,
      description: #"Total height of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"10"#,
      description: #"Horizontal left and right padding inside the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"extend_behind_notch"#,
      value: #"true"#,
      description: #"Makes the bar span the full top edge, including the area behind the notch."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"bar.colors"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background"#,
      value: #""theme.background""#,
      description: #"Background color of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border"#,
      value: #""theme.transparent""#,
      description: #"Bottom border color of the bar. Use a visible color to opt in."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.spaces"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"true"#,
      description: #"Shows or hides the built-in spaces widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""left""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"10"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""""#,
      description: #"Unused fallback icon for the spaces root widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Fallback text color for the spaces root widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.transparent""#,
      description: #"Background color behind the whole spaces block."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.transparent""#,
      description: #"Border color around the whole spaces block."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"0"#,
      description: #"Border width around the whole spaces block."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"0"#,
      description: #"Corner radius around the whole spaces block."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the spaces root container."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the spaces root container."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"0"#,
      description: #"Horizontal inner padding of the spaces root container."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"0"#,
      description: #"Vertical inner padding of the spaces root container."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"0"#,
      description: #"Root-level spacing of the spaces widget container."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1"#,
      description: #"Overall opacity of the spaces widget container."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.spaces.layout"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"8"#,
      description: #"Gap between space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"hide_empty"#,
      value: #"true"#,
      description: #"Hides spaces that have no apps."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"12"#,
      description: #"Horizontal inner padding inside each space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"2"#,
      description: #"Vertical inner padding inside each space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"4"#,
      description: #"Horizontal outer margin around the whole spaces row."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"4"#,
      description: #"Vertical outer margin around the whole spaces row."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of inactive space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"focused_corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the focused space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"focused_scale"#,
      value: #"1.0"#,
      description: #"Scale multiplier applied to the focused space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"inactive_opacity"#,
      value: #"0.85"#,
      description: #"Opacity applied to inactive space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"max_icons"#,
      value: #"4"#,
      description: #"Maximum number of app icons shown per space."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_label"#,
      value: #"true"#,
      description: #"Shows the workspace label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_icons"#,
      value: #"true"#,
      description: #"Shows app icons inside each space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_only_focused_label"#,
      value: #"false"#,
      description: #"Shows the label only on the focused space when true."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"collapse_inactive"#,
      value: #"false"#,
      description: #"Makes inactive spaces more compact when true."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"collapsed_padding_x"#,
      value: #"6"#,
      description: #"Horizontal inner padding of collapsed inactive space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"collapsed_padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of collapsed inactive space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"click_to_focus_space"#,
      value: #"true"#,
      description: #"Switches to a workspace when its pill is clicked."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"click_to_focus_app"#,
      value: #"true"#,
      description: #"Activates an app when its icon is clicked."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.spaces.text"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"size"#,
      value: #"12"#,
      description: #"Font size of the space label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"weight"#,
      value: #""semibold""#,
      description: #"Font weight of the space label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"focused_color"#,
      value: #""theme.text""#,
      description: #"Text color of the focused space label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"inactive_color"#,
      value: #""theme.text_secondary""#,
      description: #"Text color of inactive space labels."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.spaces.icons"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"size"#,
      value: #"20"#,
      description: #"Default app icon size in a space."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"4"#,
      description: #"Gap between app icons."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"3"#,
      description: #"Corner radius of app icons."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"focused_app_size"#,
      value: #"28"#,
      description: #"Size of the currently focused app icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of normal app icons."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"focused_app_border_width"#,
      value: #"1"#,
      description: #"Border width of the focused app icon."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.spaces.colors"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"active_background"#,
      value: #""theme.surface_elevated""#,
      description: #"Background color of the focused space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"inactive_background"#,
      value: #""theme.surface""#,
      description: #"Background color of inactive space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"active_border"#,
      value: #""theme.border_strong""#,
      description: #"Border color of the focused space pill."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"inactive_border"#,
      value: #""theme.transparent""#,
      description: #"Border color of inactive space pills."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"focused_app_border"#,
      value: #""theme.transparent""#,
      description: #"Border color of the focused app icon."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.front_app"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Shows or hides the front-app widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""left""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"20"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.front_app.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""􀈔""#,
      description: #"Fallback icon when no app icon is available."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.surface""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the icon and label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1.0"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.front_app.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_icon"#,
      value: #"true"#,
      description: #"Shows the focused app icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_name"#,
      value: #"true"#,
      description: #"Shows the focused app name."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"fallback_text"#,
      value: #""No App""#,
      description: #"Fallback text shown when no app name is available."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon_size"#,
      value: #"14"#,
      description: #"Display size of the app icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon_corner_radius"#,
      value: #"4"#,
      description: #"Corner radius of the displayed app icon."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.aerospace_mode"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Shows or hides the AeroSpace mode widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""left""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"30"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.aerospace_mode.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""""#,
      description: #"Leading icon of the widget. The mode-specific icon comes from content settings."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.surface""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the icon and text."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.aerospace_mode.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_icon"#,
      value: #"true"#,
      description: #"Shows the icon for the current AeroSpace layout mode."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_text"#,
      value: #"false"#,
      description: #"Shows the text label for the current AeroSpace layout mode."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"h_tiles_icon"#,
      value: #""󰕴""#,
      description: #"Icon used for horizontal tiling."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"v_tiles_icon"#,
      value: #""󰕳""#,
      description: #"Icon used for vertical tiling."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"h_accordion_icon"#,
      value: #""󰖲""#,
      description: #"Icon used for horizontal accordion."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"v_accordion_icon"#,
      value: #""󰖳""#,
      description: #"Icon used for vertical accordion."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"floating_icon"#,
      value: #""󰹙""#,
      description: #"Icon used for floating windows or containers."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"unknown_icon"#,
      value: #""󰘎""#,
      description: #"Fallback icon used when the layout cannot be detected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"h_tiles_text"#,
      value: #""h_tiles""#,
      description: #"Text label used for horizontal tiling."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"v_tiles_text"#,
      value: #""v_tiles""#,
      description: #"Text label used for vertical tiling."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"h_accordion_text"#,
      value: #""h_accordion""#,
      description: #"Text label used for horizontal accordion."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"v_accordion_text"#,
      value: #""v_accordion""#,
      description: #"Text label used for vertical accordion."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"floating_text"#,
      value: #""floating""#,
      description: #"Text label used for floating windows or containers."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"unknown_text"#,
      value: #""unknown""#,
      description: #"Fallback text label used when the layout cannot be detected."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.cpu"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Shows or hides the CPU widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"10"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .comment(#"# Example native group configuration. This is disabled by default."#),
    .comment(#"# Uncomment this block and the `group = "system"` lines below if you want"#),
    .comment(#"# battery and Wi-Fi to be rendered inside one shared native container."#),
    .blank,
    .section(
      name: #"builtins.groups.system"#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the native group on the left, center, or right side of the bar."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"order"#,
      value: #"40"#,
      description: #"Sort order among widgets in the same position."#,
      commented: true,
      prefix: #"#"#,
    ),
    .blank,
    .section(
      name: #"builtins.groups.system.style"#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.surface""#,
      description: #"Background color of the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border""#,
      description: #"Border color of the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding around the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"2"#,
      description: #"Vertical inner padding around the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between native child widgets in the group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1"#,
      description: #"Overall opacity of the native group."#,
      commented: true,
      prefix: #"#"#,
    ),
    .blank,
    .section(
      name: #"builtins.cpu.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""󰍛""#,
      description: #"Leading icon of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the widget when no content color is set."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.transparent""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.transparent""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"0"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"0"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the icon, label, and sparkline."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.cpu.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"label"#,
      value: #""CPU""#,
      description: #"Text label shown next to the sparkline."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"history_size"#,
      value: #"10"#,
      description: #"Number of samples kept in the sparkline history."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"line_width"#,
      value: #"1.8"#,
      description: #"Stroke width of the sparkline line."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"color"#,
      value: #""theme.success_secondary""#,
      description: #"Color of the sparkline and label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"sample_interval_seconds"#,
      value: #"1"#,
      description: #"Polling interval in seconds."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.battery"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"true"#,
      description: #"Shows or hides the battery widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"20"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"group"#,
      value: #""system""#,
      description: #"Optional native group id that should contain this widget."#,
      commented: true,
      prefix: #"# "#,
    ),
    .blank,
    .section(
      name: #"builtins.battery.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""🔋""#,
      description: #"Fallback or default battery icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Used when color_mode is fixed or data is unavailable."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.transparent""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.transparent""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"0"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"4"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"0"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the battery icon and text."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1.0"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.battery.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"unavailable_text"#,
      value: #""n/a""#,
      description: #"Fallback text shown when battery data is unavailable."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon_size"#,
      value: #"18"#,
      description: #"Font size of the battery icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"color_mode"#,
      value: #""fixed""#,
      description: #"Battery color mode: dynamic | fixed."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"fixed_color"#,
      value: #""theme.text""#,
      description: #"Color used only when color_mode = "fixed"."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"display_mode"#,
      value: #""expand""#,
      description: #"Display mode: none | tooltip | expand | always."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.battery.colors"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"high"#,
      value: #""theme.success""#,
      description: #"Color used for 70-100%."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"medium"#,
      value: #""theme.warning""#,
      description: #"Color used for 50-69%."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"low"#,
      value: #""theme.orange""#,
      description: #"Color used for 30-49%."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"critical"#,
      value: #""theme.danger""#,
      description: #"Color used for 0-29%."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"frame"#,
      value: #""theme.muted""#,
      description: #"Secondary palette color for the battery frame."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"overlay_outline"#,
      value: #""theme.overlay_outline""#,
      description: #"Outline color drawn behind battery overlay symbols."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"charging_overlay"#,
      value: #""theme.overlay_text""#,
      description: #"Color of the charging bolt overlay."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"external_power_overlay"#,
      value: #""theme.overlay_text""#,
      description: #"Color of the plugged-in holding overlay."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"on_hold_overlay"#,
      value: #""theme.overlay_text""#,
      description: #"Color of the on-hold pause overlay."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"unavailable"#,
      value: #""theme.muted""#,
      description: #"Color used when battery data is unavailable."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.battery.tooltip"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color used in the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.background""#,
      description: #"Background color of the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border_strong""#,
      description: #"Border color of the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"6"#,
      description: #"Vertical inner padding of the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"8"#,
      description: #"Vertical outer margin around the tooltip."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.wifi"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"true"#,
      description: #"Shows or hides the built-in Wi-Fi widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"30"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"group"#,
      value: #""system""#,
      description: #"Optional native group id that should contain this widget."#,
      commented: true,
      prefix: #"# "#,
    ),
    .blank,
    .section(
      name: #"builtins.wifi.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""""#,
      description: #"Unused fallback icon for the Wi-Fi root widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Default text color for the Wi-Fi widget root."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.transparent""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.transparent""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"0"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"0"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the signal bars and optional inline label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.wifi.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"mode"#,
      value: #""icon""#,
      description: #"Content mode: icon | inline | details."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"surface"#,
      value: #""hover""#,
      description: #"Visibility timing for inline/details content: always | hover."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"inline_separator"#,
      value: #"" | ""#,
      description: #"Separator used between enabled field values when mode = "inline"."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"disconnected_text"#,
      value: #""disconnected""#,
      description: #"Text shown for SSID when Wi-Fi is not connected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"denied_text"#,
      value: #""denied""#,
      description: #"Text shown for SSID when Wi-Fi permission is unavailable."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"active_color"#,
      value: #""theme.text""#,
      description: #"Color of active signal bars."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"inactive_color"#,
      value: #""theme.muted""#,
      description: #"Color of inactive signal bars."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.wifi.inline"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color used for inline content."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.wifi.fields"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"ssid"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi SSID for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"ipv4_address"#,
      value: #"false"#,
      description: #"Enables the primary IPv4 address for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"ipv6_address"#,
      value: #"false"#,
      description: #"Enables the primary IPv6 address for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"bssid"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi BSSID for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"interface"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi interface name for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"hardware_address"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi hardware address for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"power"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi power state for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"service_active"#,
      value: #"false"#,
      description: #"Enables the CoreWLAN service state for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"rssi"#,
      value: #"false"#,
      description: #"Enables signal strength in dBm for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"noise"#,
      value: #"false"#,
      description: #"Enables the noise floor in dBm for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"snr"#,
      value: #"false"#,
      description: #"Enables the signal-to-noise ratio in dB for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"link_quality"#,
      value: #"false"#,
      description: #"Enables the derived link quality percentage for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"tx_rate"#,
      value: #"false"#,
      description: #"Enables the current transmit rate for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"channel"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi channel for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"channel_band"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi band for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"channel_width"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi channel width for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"security"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi security mode for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"phy_mode"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi PHY mode for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"interface_mode"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi interface mode for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"country_code"#,
      value: #"false"#,
      description: #"Enables the current Wi-Fi country code for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"roaming"#,
      value: #"false"#,
      description: #"Enables whether access-point roaming was detected for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"ssid_changed_at"#,
      value: #"false"#,
      description: #"Enables the last SSID change timestamp for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"interface_changed_at"#,
      value: #"false"#,
      description: #"Enables the last interface change timestamp for inline and details modes."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.wifi.popup"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color used in the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.background""#,
      description: #"Background color of the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border_strong""#,
      description: #"Border color of the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"6"#,
      description: #"Vertical inner padding of the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"8"#,
      description: #"Vertical outer margin around the Wi-Fi popup."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.volume"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Shows or hides the volume widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"20"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.volume.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""""#,
      description: #"Leading icon of the compact widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.transparent""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.transparent""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"0"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"0"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"8"#,
      description: #"Gap between the icon, label, and slider."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1.0"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.volume.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"muted_icon"#,
      value: #""􀊢""#,
      description: #"Icon shown when audio is muted."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"low_icon"#,
      value: #""􀊤""#,
      description: #"Icon shown for low volume."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"high_icon"#,
      value: #""􀊦""#,
      description: #"Icon shown for high volume."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_percentage"#,
      value: #"true"#,
      description: #"Shows the volume percentage text."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"min"#,
      value: #"0"#,
      description: #"Minimum slider and display value."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"max"#,
      value: #"100"#,
      description: #"Maximum slider and display value."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"step"#,
      value: #"1"#,
      description: #"Slider step size."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.volume.slider"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"expand_to_slider_on_hover"#,
      value: #"true"#,
      description: #"Expands from compact mode to slider mode on hover."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"width"#,
      value: #"80"#,
      description: #"Width of the slider when shown."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"true"#,
      description: #"Shows or hides the unified calendar widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"60"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"popup_mode"#,
      value: #""month""#,
      description: #"Popup mode: none | upcoming | month."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""""#,
      description: #"Optional leading icon for the calendar anchor."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Default text color of the anchor."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.surface""#,
      description: #"Background color of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border""#,
      description: #"Border color of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between anchor contents."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1.0"#,
      description: #"Overall opacity of the anchor widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.anchor"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"layout"#,
      value: #""stack""#,
      description: #"Anchor layout: item | stack | inline."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"item_format"#,
      value: #""EEE, MMM d""#,
      description: #"Format used when anchor layout is item."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"top_format"#,
      value: #""HH:mm""#,
      description: #"Top line format used in stack or inline layouts."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"bottom_format"#,
      value: #""d. MMM""#,
      description: #"Bottom or second line format used in stack or inline layouts."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"line_spacing"#,
      value: #"0"#,
      description: #"Vertical spacing between top and bottom lines in stack layout."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"top_text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the top line."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"bottom_text_color"#,
      value: #""theme.text_secondary""#,
      description: #"Text color of the bottom line."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.composer"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"create_title"#,
      value: #""New Appointment""#,
      description: #"Panel title shown when creating an appointment."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"edit_title"#,
      value: #""Edit Appointment""#,
      description: #"Panel title shown when editing an appointment."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"title_label"#,
      value: #""Title""#,
      description: #"Label shown above the title field."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"location_label"#,
      value: #""Location""#,
      description: #"Label shown above the location field."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"calendar_label"#,
      value: #""Calendar""#,
      description: #"Label shown above the calendar picker."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"start_label"#,
      value: #""Begin""#,
      description: #"Label shown for the start time."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"end_label"#,
      value: #""End""#,
      description: #"Label shown for the end time."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"all_day_label"#,
      value: #""All day""#,
      description: #"Label shown for all-day events."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"travel_time_label"#,
      value: #""Travel time""#,
      description: #"Label shown for the travel-time picker."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"alert_label"#,
      value: #""Alert""#,
      description: #"Label shown above the alerts section."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"add_alert_label"#,
      value: #""Add alert""#,
      description: #"Button label used to add another alert row."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"open_calendar_label"#,
      value: #""Calendar""#,
      description: #"Footer button label used to open Calendar.app."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"cancel_label"#,
      value: #""Cancel""#,
      description: #"Footer cancel button label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"save_label"#,
      value: #""Save""#,
      description: #"Footer primary button label when creating."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"update_label"#,
      value: #""Update""#,
      description: #"Footer primary button label when editing."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"remove_label"#,
      value: #""Remove""#,
      description: #"Footer destructive button label."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"delete_confirmation_title"#,
      value: #""Remove appointment?""#,
      description: #"Delete confirmation title."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"delete_confirmation_message"#,
      value: #""This action cannot be undone.""#,
      description: #"Delete confirmation message."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"title_placeholder"#,
      value: #""What are you doing?""#,
      description: #"Placeholder text for the composer title field."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"location_placeholder"#,
      value: #""Where are you going?""#,
      description: #"Placeholder text for the composer location field."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"default_calendar_name"#,
      value: #""""#,
      description:
        #"Default calendar name used when creating new appointments. Empty selects the first available writable calendar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"default_alert"#,
      value: #""1_hour""#,
      description:
        #"Default alert lead time: none | at_time | 5_minutes | 10_minutes | 15_minutes | 30_minutes | 1_hour | 1_day."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"default_travel_time"#,
      value: #""none""#,
      description:
        #"Default travel time: none | 5_minutes | 10_minutes | 15_minutes | 20_minutes | 30_minutes | 45_minutes | 1_hour | 90_minutes | 2_hours."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.composer.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.background""#,
      description: #"Background color of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border_strong""#,
      description: #"Border and divider color of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"10"#,
      description: #"Corner radius of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"14"#,
      description: #"Horizontal inner padding of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"14"#,
      description: #"Vertical inner padding of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"header_text_color"#,
      value: #""theme.text""#,
      description: #"Header title color of the appointment composer panel."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .comment(
      #"# Optional composer label overrides. Leave these commented to use the system language."#,
    ),
    .comment(#"# Uncomment only the labels you want to override manually."#),
    .section(
      name: #"builtins.calendar.composer.alert_labels"#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"none"#,
      value: #""None""#,
      description: #"Label shown for no alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"at_time"#,
      value: #""At time of event""#,
      description: #"Label shown for alerts at event time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"5_minutes"#,
      value: #""5 minutes before""#,
      description: #"Label shown for a 5-minute alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"10_minutes"#,
      value: #""10 minutes before""#,
      description: #"Label shown for a 10-minute alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"15_minutes"#,
      value: #""15 minutes before""#,
      description: #"Label shown for a 15-minute alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"30_minutes"#,
      value: #""30 minutes before""#,
      description: #"Label shown for a 30-minute alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"1_hour"#,
      value: #""1 hour before""#,
      description: #"Label shown for a 1-hour alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"1_day"#,
      value: #""1 day before""#,
      description: #"Label shown for a 1-day alert."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"custom"#,
      value: #""Custom""#,
      description: #"Label shown for a custom alert lead time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.composer.travel_time_labels"#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"none"#,
      value: #""None""#,
      description: #"Label shown when no travel time is set."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"5_minutes"#,
      value: #""5 minutes""#,
      description: #"Label shown for 5 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"10_minutes"#,
      value: #""10 minutes""#,
      description: #"Label shown for 10 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"15_minutes"#,
      value: #""15 minutes""#,
      description: #"Label shown for 15 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"20_minutes"#,
      value: #""20 minutes""#,
      description: #"Label shown for 20 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"30_minutes"#,
      value: #""30 minutes""#,
      description: #"Label shown for 30 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"45_minutes"#,
      value: #""45 minutes""#,
      description: #"Label shown for 45 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"1_hour"#,
      value: #""1 hour""#,
      description: #"Label shown for 1 hour of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"90_minutes"#,
      value: #""1.5 hours""#,
      description: #"Label shown for 90 minutes of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"2_hours"#,
      value: #""2 hours""#,
      description: #"Label shown for 2 hours of travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .entry(
      key: #"custom"#,
      value: #""Custom""#,
      description: #"Label shown for a custom travel time."#,
      commented: true,
      prefix: #"#"#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.upcoming.events"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"days"#,
      value: #"3"#,
      description: #"Number of days of upcoming events shown in the popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"exclude_past_events"#,
      value: #"false"#,
      description: #"Hides already-finished or already-started items from today's section when true."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.upcoming.popup"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.background""#,
      description: #"Background color of the upcoming popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border_strong""#,
      description: #"Border color of the upcoming popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the upcoming popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"10"#,
      description: #"Corner radius of the upcoming popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"10"#,
      description: #"Horizontal inner padding of the upcoming popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"8"#,
      description: #"Vertical inner padding of the upcoming popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"8"#,
      description: #"Horizontal outer margin around the whole popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"8"#,
      description: #"Vertical outer margin around the whole popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"8"#,
      description: #"Vertical spacing between popup sections."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.appointments"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"item_indent"#,
      value: #"8"#,
      description: #"Left indent for appointment rows."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"event_text_color"#,
      value: #""theme.text_secondary""#,
      description: #"Text color of appointment rows."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"empty_text_color"#,
      value: #""theme.text_tertiary""#,
      description: #"Text color of the appointments empty state."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"secondary_text_color"#,
      value: #""theme.accent""#,
      description: #"Text color of secondary appointment details and section headings."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"travel_text_color"#,
      value: #""theme.muted_secondary""#,
      description: #"Muted text color used for travel-time and end-time rows."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"empty_text"#,
      value: #""No appointments""#,
      description: #"Text shown when an appointment section has no events."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_calendar_name"#,
      value: #"false"#,
      description: #"Shows the source calendar name for appointments."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_all_day_label"#,
      value: #"true"#,
      description: #"Shows "All day" for all-day events except birthdays, which omit it."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_holiday_all_day_label"#,
      value: #"false"#,
      description: #"Shows "All day" for all-day holiday-calendar events."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"all_day_label"#,
      value: #""All day""#,
      description: #"Text shown for all-day events when show_all_day_label is true."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_location"#,
      value: #"true"#,
      description: #"Shows the event location line when present."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"location_icon"#,
      value: #""""#,
      description: #"Leading icon shown for location rows. Set to an empty string to hide the icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"location_icon_color"#,
      value: #""theme.accent""#,
      description: #"Color of the location icon. When omitted, secondary_text_color is used."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_travel_time"#,
      value: #"true"#,
      description: #"Shows the travel-time line when present."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_end_time"#,
      value: #"true"#,
      description: #"Shows the end-time line for timed appointments."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"travel_icon"#,
      value: #""""#,
      description: #"Leading icon shown for travel-time rows."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"travel_icon_color"#,
      value: #""theme.muted_secondary""#,
      description: #"Color of the travel-time icon."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_alert_icon"#,
      value: #"false"#,
      description: #"Shows a small alert icon on timed appointments with at least one non-travel alert."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"alert_icon"#,
      value: #""""#,
      description: #"Optional icon shown when show_alert_icon is true and the event has an alert."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"alert_icon_color"#,
      value: #""theme.muted_secondary""#,
      description: #"Color of the alert icon."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.birthdays"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_birthdays"#,
      value: #"true"#,
      description: #"Includes birthday calendars in both month and upcoming appointment lists."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"birthdays_show_age"#,
      value: #"true"#,
      description: #"Shows parsed ages for birthday appointments when available."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"birthday_icon"#,
      value: #""""#,
      description: #"Leading icon shown for birthday appointments."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"birthday_icon_color"#,
      value: #""theme.accent_soft""#,
      description: #"Color of the birthday icon. When omitted, event_text_color is used."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.filters"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"included_calendar_names"#,
      value: #"[]"#,
      description: #"Optional allowlist of visible Calendar.app names. Empty means all calendars are eligible."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"excluded_calendar_names"#,
      value: #"[]"#,
      description: #"Optional denylist of visible Calendar.app names applied after the allowlist."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"included_calendar_ids"#,
      value: #"[]"#,
      description: #"Optional advanced allowlist of exact calendar identifiers."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"excluded_calendar_ids"#,
      value: #"[]"#,
      description: #"Optional advanced denylist of exact calendar identifiers."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"included_calendar_source_ids"#,
      value: #"[]"#,
      description: #"Optional advanced allowlist of exact calendar source identifiers."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"excluded_calendar_source_ids"#,
      value: #"[]"#,
      description: #"Optional advanced denylist of exact calendar source identifiers."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.month.popup.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.background""#,
      description: #"Background color of the month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border_strong""#,
      description: #"Border color of the month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"14"#,
      description: #"Corner radius of the month popup. Set to 0 for square corners."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"10"#,
      description: #"Horizontal inner padding of the month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"8"#,
      description: #"Vertical inner padding of the month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"8"#,
      description: #"Gap between calendar and appointments areas and internal popup sections."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"8"#,
      description: #"Horizontal outer margin around the whole month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"8"#,
      description: #"Vertical outer margin around the whole month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.month.popup.calendar"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_week_numbers"#,
      value: #"true"#,
      description: #"Shows week numbers in the calendar grid."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_event_indicators"#,
      value: #"true"#,
      description: #"Shows dots under days that contain events."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"header_text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the month header and appointments title."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"weekday_text_color"#,
      value: #""theme.accent""#,
      description: #"Text color of the weekday labels."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"first_weekday"#,
      value: #"2"#,
      description:
        #"Optional first weekday override. 1 = Sunday, 2 = Monday, ... 7 = Saturday. When omitted, EasyBar uses the current calendar setting."#,
      commented: true,
      prefix: #"# "#,
    ),
    .entry(
      key: #"weekday_format"#,
      value: #""dd""#,
      description: #"Weekday label format: d | dd | ddd. dddd is not allowed."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"weekday_symbols"#,
      value: #"["M", "T", "W", "T", "F", "S", "S"]"#,
      description:
        #"Optional custom weekday labels in Monday-first order. Must contain exactly 7 entries from Monday to Sunday."#,
      commented: true,
      prefix: #"# "#,
    ),
    .entry(
      key: #"day_text_color"#,
      value: #""theme.text_secondary""#,
      description: #"Text color of days in the current month."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"outside_month_text_color"#,
      value: #""theme.outside_month""#,
      description: #"Text color of leading and trailing days outside the current month."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"today_cell_background_color"#,
      value: #""""#,
      description: #"Background color of today's day cell when it is not selected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"today_cell_border_color"#,
      value: #""theme.danger""#,
      description: #"Border color of today's day cell when it is not selected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"today_cell_border_width"#,
      value: #"1.4"#,
      description: #"Border width of today's day cell when it is not selected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"indicator_color"#,
      value: #""theme.accent_soft""#,
      description: #"Default color of day event indicators when an event has no calendar color."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.month.popup.selection"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"selected_text_color"#,
      value: #""theme.selection_text""#,
      description: #"Text color of selected day cells."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"selected_background_color"#,
      value: #""theme.selection_background""#,
      description: #"Background color of selected day cells."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"selection_date_format"#,
      value: #""yyyy-MM-dd""#,
      description: #"Date header format used when a multi-day range is selected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"selection_date_separator"#,
      value: #"" - ""#,
      description: #"Separator used between start and end dates when a date range is selected."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"allows_range_selection"#,
      value: #"true"#,
      description: #"Allows selecting a date range by dragging across days."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"reset_selection_on_third_tap"#,
      value: #"true"#,
      description: #"Reserved selection behavior flag for the month popup."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.month.popup.agenda"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"layout"#,
      value: #""calendar_appointments_vertical""#,
      description:
        #"Popup layout: calendar_appointments_horizontal | appointments_calendar_horizontal | calendar_appointments_vertical | appointments_calendar_vertical."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"appointments_scrollable"#,
      value: #"true"#,
      description: #"Makes the appointments area scroll vertically when true."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"appointments_min_height"#,
      value: #"180"#,
      description:
        #"Minimum height of the appointments area. Set equal to appointments_max_height for a fixed height."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"appointments_max_height"#,
      value: #"240"#,
      description:
        #"Maximum height of the appointments area. Set equal to appointments_min_height for a fixed height."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"agenda_title"#,
      value: #""Appointments""#,
      description: #"Title shown above the appointments list."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"max_visible_appointments"#,
      value: #"8"#,
      description: #"Maximum number of visible appointments when scrolling is disabled."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.month.popup.anchor"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"date_format"#,
      value: #""EEE d MMM""#,
      description: #"Date format used when popup_mode = "month" and anchor layout = "item"."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color used when popup_mode = "month"."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"show_date_text"#,
      value: #"true"#,
      description: #"Shows the date text when popup_mode = "month"."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.calendar.month.popup.today_button"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"title"#,
      value: #""Today""#,
      description: #"Title of the Today button."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.today_button_border""#,
      description: #"Border color of the Today button."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1.5"#,
      description: #"Border width of the Today button."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""""#,
      description: #"Optional leading icon of the Today button, for example 󰃭."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.time"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Shows or hides the time widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"40"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.time.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""🕒""#,
      description: #"Leading icon of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.surface""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the icon and text."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1.0"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.time.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"format"#,
      value: #""HH:mm""#,
      description: #"Time format string."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.date"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"enabled"#,
      value: #"false"#,
      description: #"Shows or hides the date widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"position"#,
      value: #""right""#,
      description: #"Places the widget on the left, center, or right side of the bar."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"order"#,
      value: #"50"#,
      description: #"Sort order among widgets in the same position."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.date.style"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"icon"#,
      value: #""📅""#,
      description: #"Leading icon of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"text_color"#,
      value: #""theme.text""#,
      description: #"Text color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"background_color"#,
      value: #""theme.surface""#,
      description: #"Background color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_color"#,
      value: #""theme.border""#,
      description: #"Border color of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"border_width"#,
      value: #"1"#,
      description: #"Border width of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"corner_radius"#,
      value: #"8"#,
      description: #"Corner radius of the widget background."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_x"#,
      value: #"0"#,
      description: #"Horizontal outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"margin_y"#,
      value: #"0"#,
      description: #"Vertical outer margin around the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_x"#,
      value: #"8"#,
      description: #"Horizontal inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"padding_y"#,
      value: #"4"#,
      description: #"Vertical inner padding of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"spacing"#,
      value: #"6"#,
      description: #"Gap between the icon and text."#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"opacity"#,
      value: #"1.0"#,
      description: #"Overall opacity of the widget."#,
      commented: false,
      prefix: #""#,
    ),
    .blank,
    .section(
      name: #"builtins.date.content"#,
      commented: false,
      prefix: #""#,
    ),
    .entry(
      key: #"format"#,
      value: #""yyyy-MM-dd""#,
      description: #"Date format string."#,
      commented: false,
      prefix: #""#,
    ),
  ]

  /// Sections whose keys are intentionally open-ended.
  private static let freeFormSections: Set<String> = [
    "app.env",
    "builtins.calendar.composer.alert_labels",
    "builtins.calendar.composer.travel_time_labels",
  ]

  private static let placementKeys: Set<String> = [
    "enabled", "position", "order", "group",
  ]

  private static let widgetStyleKeys: Set<String> = [
    "icon", "text_color", "background_color", "border_color", "border_width",
    "corner_radius", "margin_x", "margin_y", "padding_x", "padding_y", "spacing",
    "opacity",
  ]

  private static let knownKeysBySection: [String: Set<String>] = {
    var sections: [String: [String]] = [:]

    func addSection(_ path: String) {
      if sections[path] == nil {
        sections[path] = []
      }

      guard !path.isEmpty else { return }
      let parts = path.split(separator: ".").map(String.init)
      guard !parts.isEmpty else { return }

      addKey(section: "", key: parts[0])

      if parts.count > 1 {
        for index in 1..<parts.count {
          let parent = parts[..<index].joined(separator: ".")
          addKey(section: parent, key: parts[index])
        }
      }
    }

    func addKey(section: String, key: String) {
      if sections[section] == nil {
        sections[section] = []
      }

      if sections[section]?.contains(key) == false {
        sections[section]?.append(key)
      }
    }

    var currentSection = ""
    addSection(currentSection)

    for line in lines {
      switch line {
      case .section(let name, _, _):
        currentSection = name
        addSection(name)
      case .entry(let key, _, _, _, _):
        addKey(section: currentSection, key: key)
      case .blank, .comment:
        continue
      }
    }

    addSection("theme.colors")
    addKey(section: "theme", key: "colors")

    return sections.mapValues(Set.init)
  }()

  /// Returns true when a section accepts arbitrary keys.
  public static func isFreeFormSection(_ path: String) -> Bool {
    freeFormSections.contains(path)
  }

  /// Returns known keys for one TOML section path.
  public static func knownKeys(for path: String) -> Set<String> {
    if isBuiltinGroup(path) {
      return placementKeys.union(["style"])
    }

    if isBuiltinGroupStyle(path) {
      return widgetStyleKeys
    }

    return knownKeysBySection[path] ?? []
  }

  /// Returns true when a TOML section path is known.
  public static func isKnownSection(_ path: String) -> Bool {
    knownKeysBySection[path] != nil
      || freeFormSections.contains(path)
      || isBuiltinGroup(path)
      || isBuiltinGroupStyle(path)
  }

  private static func isBuiltinGroup(_ path: String) -> Bool {
    let components = path.split(separator: ".")
    return components.count == 3
      && components[0] == "builtins"
      && components[1] == "groups"
  }

  private static func isBuiltinGroupStyle(_ path: String) -> Bool {
    let components = path.split(separator: ".")
    return components.count == 4
      && components[0] == "builtins"
      && components[1] == "groups"
      && components[3] == "style"
  }
}
