#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "Sources/EasyBarApp/Events/event_catalog.json"
EVENT_TOKENS_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar/event_tokens.lua"
LUA_API_BASE_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar_api.base.lua"
LUA_API_EVENTS_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar_api.events.lua"
LUA_API_STUB_PATH = ROOT / "Sources/EasyBarApp/Lua/easybar_api.lua"
LUA_API_INSERT_MARKER = "-- GENERATED SECTION: easybar.events"


def load_manifest() -> dict:
    """Load the event catalog manifest used to generate Lua event files."""
    return json.loads(MANIFEST_PATH.read_text())


def event_token_line(lua_field: str, runtime_name: str, indent: str = "\t") -> str:
    """Render one Lua table entry for an event token."""
    return f'{indent}{lua_field} = make_event_token("{runtime_name}"),'


def quoted_union(values: list[str]) -> list[str]:
    """Render EmmyLua union entries for a list of string literal values."""
    return [f'---| \'"{value}"\'' for value in values]


def render_event_tokens(manifest: dict) -> str:
    """Render the generated `easybar.events` Lua runtime module."""
    forced = manifest["forcedEvent"]
    app_events = manifest["appEvents"]
    widget_groups = {
        group["name"]: group
        for group in manifest["widgetGroups"]
    }
    mouse_buttons = manifest["mouseButtons"]
    scroll_directions = manifest["scrollDirections"]

    lines = [
        "--- Module contract:",
        "--- Owns reusable `easybar.events` tokens, mouse constants, and event-name normalization.",
        "--- Returns one table with `tokens`, `driver_events`, and `normalize(...)`.",
        "-- This file is generated by scripts/generate_event_catalog.py. Do not edit by hand.",
        "--- Event token module table.",
        "local M = {}",
        "",
        "---- App events that may be requested from the Swift driver.",
        "local DRIVER_EVENTS = {",
    ]

    # Driver events are handled by app-level Swift event sources.
    for event in app_events:
        if event.get("driver"):
            lines.append(f'\t{event["luaField"]} = true,')

    # The forced update event is always considered a driver event.
    lines.append(f'\t{forced["luaField"]} = true,')
    lines.extend(
        [
            "}",
            "",
            "--- Mouse button constants exposed through `easybar.events.mouse`.",
            "local MOUSE_BUTTONS = {",
        ]
    )

    for value in mouse_buttons:
        lines.append(f"\t{value} = \"{value}\",")

    lines.extend(
        [
            "}",
            "",
            "--- Scroll direction constants exposed through `easybar.events.mouse`.",
            "local SCROLL_DIRECTIONS = {",
        ]
    )

    for value in scroll_directions:
        lines.append(f"\t{value} = \"{value}\",")

    lines.extend(
        [
            "}",
            "",
            "--- Wraps one runtime event name in a reusable subscribe token.",
            "local function make_event_token(name)",
            "\treturn {",
            "\t\tname = name,",
            "\t}",
            "end",
            "",
            "---- Public event token namespace exposed to widgets.",
            "M.tokens = {",
            event_token_line(forced["luaField"], forced["runtimeName"]),
        ]
    )

    for event in app_events:
        lines.append(event_token_line(event["luaField"], event["runtimeName"]))

    mouse = widget_groups["mouse"]
    lines.extend(["\tmouse = {"])
    for event in mouse["events"]:
        lines.append(
            event_token_line(
                event["luaField"],
                event["runtimeName"],
                indent="\t\t",
            )
        )

    lines.append("")
    for value in mouse_buttons:
        lines.append(f"\t\t{value}_button = MOUSE_BUTTONS.{value},")

    lines.append("")
    for value in scroll_directions:
        lines.append(f"\t\t{value}_scroll = SCROLL_DIRECTIONS.{value},")

    lines.extend(
        [
            "",
            "\t\tbuttons = MOUSE_BUTTONS,",
            "\t\tdirections = SCROLL_DIRECTIONS,",
            "\t},",
        ]
    )

    slider = widget_groups["slider"]
    lines.extend(["\tslider = {"])
    for event in slider["events"]:
        lines.append(
            event_token_line(
                event["luaField"],
                event["runtimeName"],
                indent="\t\t",
            )
        )

    lines.extend(
        [
            "\t},",
            "}",
            "",
            "---- Driver event lookup table used by subscription discovery.",
            "M.driver_events = DRIVER_EVENTS",
            "",
            "--- Extracts the runtime event name from one `easybar.events` token.",
            "function M.normalize(event)",
            "\tassert(",
            '\t\ttype(event) == "table" and type(event.name) == "string" and event.name ~= "",',
            '\t\t"easybar.subscribe(...) requires easybar.events values"',
            "\t)",
            "\treturn event.name",
            "end",
            "",
            "return M",
            "",
        ]
    )

    return "\n".join(lines)


def render_lua_api_block(manifest: dict) -> str:
    """Render EmmyLua annotations for the generated EasyBar event API."""
    forced = manifest["forcedEvent"]
    app_events = manifest["appEvents"]
    widget_groups = {
        group["name"]: group
        for group in manifest["widgetGroups"]
    }
    mouse_buttons = manifest["mouseButtons"]
    scroll_directions = manifest["scrollDirections"]

    # Include all event names that may be passed through the runtime event system.
    event_names = (
        ["interval", forced["runtimeName"]]
        + [event["runtimeName"] for event in app_events]
        + [
            event["runtimeName"]
            for group in manifest["widgetGroups"]
            for event in group["events"]
        ]
    )
    event_docs = {
        "interval": "Internal timer callback name used when `interval` and `on_interval` are configured on a node.",
        forced["runtimeName"]: forced["doc"],
    }
    event_docs.update({event["runtimeName"]: event["doc"] for event in app_events})
    event_docs.update({
        event["runtimeName"]: event["doc"]
        for group in manifest["widgetGroups"]
        for event in group["events"]
    })

    lines = [
        "-- EasyBar generated event stub. Do not edit by hand.",
        "-- Source of truth: Sources/EasyBarApp/Events/event_catalog.json",
        "-- Regenerate with: scripts/generate_event_catalog.py",
        "---Canonical runtime event-name strings carried inside `EasyBarEventToken.name`.",
        "---In normal widget code, prefer `easybar.events.*` tokens over comparing raw strings.",
        "---@alias EasyBarEventName",
    ]
    for event_name in event_names:
        lines.extend([
            f'---{event_docs[event_name]}',
            f'---| \'"{event_name}"\'',
        ])
    lines.extend([
        "",
        "---Structured network-specific fields that may be present on network-related events.",
        "---@class EasyBarNetworkEventData",
        "---@field primary_interface_is_tunnel? boolean Whether the current primary network interface is a tunnel.",
        "---@field interface_name? string The network interface name when provided.",
        "",
        "---Structured power-specific fields that may be present on charging or power-source events.",
        "---@class EasyBarPowerEventData",
        "---@field charging? boolean Whether the current power source is charging.",
        "",
        "---Structured audio-specific fields that may be present on mute or volume events.",
        "---@class EasyBarAudioEventData",
        "---@field muted? boolean Whether the current audio output is muted.",
        "---@field value? number The current audio-related value when provided.",
        "",
        "---The event payload object delivered to event handlers.",
        "---Different event families populate different optional fields.",
        "---@class EasyBarEvent",
        "---@field name string The dispatched event name.",
        "---@field widget_id? string The subscribed widget id receiving the event.",
        "---@field target_widget_id? string The concrete node id that received the interaction.",
        "---@field app_name? string The focused app name for app-switch style events.",
        "---@field button? EasyBarMouseButton|string The mouse button name, usually `left`, `right`, or `middle`.",
        "---@field direction? EasyBarScrollDirection|string The scroll direction, usually `up`, `down`, `left`, or `right`.",
        "---@field value? number|string|boolean The event value for slider and driver updates.",
        "---@field delta_x? number Horizontal scroll delta.",
        "---@field delta_y? number Vertical scroll delta.",
        "---@field network? EasyBarNetworkEventData Structured network event data.",
        "---@field power? EasyBarPowerEventData Structured power event data.",
        "---@field audio? EasyBarAudioEventData Structured audio event data.",
        "",
        "---The callback signature used by `node:subscribe(...)` and `easybar.subscribe(...)`.",
        "---@alias EasyBarEventHandler fun(event: EasyBarEvent)",
        "",
        "---Opaque subscribe token object passed through from `easybar.events.*`.",
        "---@class EasyBarEventToken",
        "---@field name EasyBarEventName The canonical runtime event name sent by EasyBar.",
        "",
        "---Convenience constants mirrored under `easybar.events.mouse.buttons`.",
        "---@class EasyBarMouseButtons",
    ])

    for value in mouse_buttons:
        description = {
            "left": "Matches the primary mouse button.",
            "right": "Matches the secondary mouse button.",
            "middle": "Matches the middle mouse button.",
        }[value]
        lines.append(f"---@field {value} EasyBarMouseButton {description}")

    lines.extend(["", "---Convenience constants mirrored under `easybar.events.mouse.directions`.", "---@class EasyBarScrollDirections"])
    for value in scroll_directions:
        description = {
            "up": "Matches upward scrolling.",
            "down": "Matches downward scrolling.",
            "left": "Matches leftward scrolling.",
            "right": "Matches rightward scrolling.",
        }[value]
        lines.append(f"---@field {value} EasyBarScrollDirection {description}")

    mouse = widget_groups["mouse"]
    lines.extend(["", "---Mouse-specific interaction tokens and convenience constants nested under `easybar.events.mouse`.", "---@class EasyBarMouseEvents"])
    for event in mouse["events"]:
        lines.append(
            f'---@field {event["luaField"]}? EasyBarEventToken {event["doc"]}'
        )

    for value in mouse_buttons:
        lines.append(
            f'---@field {value}_button EasyBarMouseButton Constant for `event.button == "{value}"`.'
        )

    for value in scroll_directions:
        lines.append(
            f'---@field {value}_scroll EasyBarScrollDirection Constant for `event.direction == "{value}"`.'
        )

    lines.extend(
        [
            "---@field buttons EasyBarMouseButtons Nested mouse-button constants.",
            "---@field directions EasyBarScrollDirections Nested scroll-direction constants.",
            "",
            "---Slider-specific interaction tokens nested under `easybar.events.slider`.",
            "---@class EasyBarSliderEvents",
        ]
    )

    slider = widget_groups["slider"]
    for event in slider["events"]:
        lines.append(
            f'---@field {event["luaField"]}? EasyBarEventToken {event["doc"]}'
        )

    lines.extend(["", "---Namespace object exposed as `easybar.events`.", "---Use these tokens when subscribing widgets instead of hard-coding event-name strings.", "---@class EasyBarEvents"])
    lines.append(
        f'---@field {forced["luaField"]}? EasyBarEventToken {forced["doc"]}'
    )

    for event in app_events:
        lines.append(
            f'---@field {event["luaField"]}? EasyBarEventToken {event["doc"]}'
        )

    for group in manifest["widgetGroups"]:
        lines.append(
            f'---@field {group["name"]}? EasyBar{group["name"].title()}Events {group["doc"]}'
        )

    lines.append("")
    return "\n".join(lines)


def rebuild_lua_api_stub(manifest: dict) -> None:
    """Regenerate the standalone Lua API stub from the base file and event annotations."""
    generated_events = render_lua_api_block(manifest)
    LUA_API_EVENTS_PATH.write_text(generated_events)

    base = LUA_API_BASE_PATH.read_text()
    if LUA_API_INSERT_MARKER not in base:
        raise RuntimeError(
            "could not find generated event API insertion marker in easybar_api.base.lua"
        )

    combined = base.replace(LUA_API_INSERT_MARKER,
                            generated_events, 1).rstrip()
    LUA_API_STUB_PATH.write_text(f"{combined}\n")


def main() -> None:
    """Generate Lua runtime event tokens and API annotation files."""
    manifest = load_manifest()

    EVENT_TOKENS_PATH.write_text(render_event_tokens(manifest))
    rebuild_lua_api_stub(manifest)


if __name__ == "__main__":
    main()
