#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "Sources/EasyBar/Events/event_catalog.json"
EVENT_TOKENS_PATH = ROOT / "Sources/EasyBar/Lua/easybar/event_tokens.lua"
LUA_API_BASE_PATH = ROOT / "Sources/EasyBar/Lua/easybar_api.base.lua"
LUA_API_EVENTS_PATH = ROOT / "Sources/EasyBar/Lua/easybar_api.events.lua"
LUA_API_STUB_PATH = ROOT / "Sources/EasyBar/Lua/easybar_api.lua"
LUA_API_INSERT_MARKER = "-- GENERATED EVENT API"


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def event_token_line(lua_field: str, runtime_name: str, indent: str = "\t") -> str:
    return f'{indent}{lua_field} = make_event_token("{runtime_name}"),'


def quoted_union(values: list[str]) -> list[str]:
    return [f'---| \'"{value}"\'' for value in values]


def render_event_tokens(manifest: dict) -> str:
    forced = manifest["forcedEvent"]
    app_events = manifest["appEvents"]
    widget_groups = {group["name"]: group for group in manifest["widgetGroups"]}
    mouse_buttons = manifest["mouseButtons"]
    scroll_directions = manifest["scrollDirections"]

    lines = [
        "--- Module contract:",
        "--- Owns reusable `easybar.events` tokens, mouse constants, and event-name normalization.",
        "--- Returns one table with `tokens`, `driver_events`, and `normalize(...)`.",
        "-- This file is generated by scripts/generate_event_catalog.py. Do not edit by hand.",
        "local M = {}",
        "",
        "local DRIVER_EVENTS = {",
    ]

    for event in app_events:
        if event.get("driver"):
            lines.append(f'\t{event["luaField"]} = true,')
    lines.append(f'\t{forced["luaField"]} = true,')
    lines.extend(
        [
            "}",
            "",
            "local MOUSE_BUTTONS = {",
        ]
    )

    for value in mouse_buttons:
        lines.append(f"\t{value} = \"{value}\",")

    lines.extend(
        [
            "}",
            "",
            "local SCROLL_DIRECTIONS = {",
        ]
    )

    for value in scroll_directions:
        lines.append(f"\t{value} = \"{value}\",")

    lines.extend(
        [
            "}",
            "",
            "--- Wraps one runtime event name in a reusable subscribe token.",
            "local function make_event_token(name)",
            "\treturn {",
            "\t\tname = name,",
            "\t}",
            "end",
            "",
            "M.tokens = {",
            event_token_line(forced["luaField"], forced["runtimeName"]),
        ]
    )

    for event in app_events:
        lines.append(event_token_line(event["luaField"], event["runtimeName"]))

    mouse = widget_groups["mouse"]
    lines.extend(["\tmouse = {"])
    for event in mouse["events"]:
        lines.append(event_token_line(event["luaField"], event["runtimeName"], indent="\t\t"))
    lines.append("")
    for value in mouse_buttons:
        lines.append(f"\t\t{value}_button = MOUSE_BUTTONS.{value},")
    lines.append("")
    for value in scroll_directions:
        lines.append(f"\t\t{value}_scroll = SCROLL_DIRECTIONS.{value},")
    lines.extend(
        [
            "",
            "\t\tbuttons = MOUSE_BUTTONS,",
            "\t\tdirections = SCROLL_DIRECTIONS,",
            "\t},",
        ]
    )

    slider = widget_groups["slider"]
    lines.extend(["\tslider = {"])
    for event in slider["events"]:
        lines.append(event_token_line(event["luaField"], event["runtimeName"], indent="\t\t"))
    lines.extend(
        [
            "\t},",
            "}",
            "",
            "M.driver_events = DRIVER_EVENTS",
            "",
            "--- Extracts the runtime event name from one `easybar.events` token.",
            "function M.normalize(event)",
            "\tassert(",
            '\t\ttype(event) == "table" and type(event.name) == "string" and event.name ~= "",',
            '\t\t"easybar.subscribe(...) requires easybar.events values"',
            "\t)",
            "\treturn event.name",
            "end",
            "",
            "return M",
            "",
        ]
    )

    return "\n".join(lines)


def render_lua_api_block(manifest: dict) -> str:
    forced = manifest["forcedEvent"]
    app_events = manifest["appEvents"]
    widget_groups = {group["name"]: group for group in manifest["widgetGroups"]}
    mouse_buttons = manifest["mouseButtons"]
    scroll_directions = manifest["scrollDirections"]

    event_names = (
        ["interval", forced["runtimeName"]]
        + [event["runtimeName"] for event in app_events]
        + [event["runtimeName"] for group in manifest["widgetGroups"] for event in group["events"]]
    )

    lines = [
        "---@alias EasyBarEventName",
        *quoted_union(event_names),
        "",
        "---@class EasyBarNetworkEventData",
        "---@field primary_interface_is_tunnel? boolean Whether the current primary network interface is a tunnel.",
        "---@field interface_name? string The network interface name when provided.",
        "",
        "---@class EasyBarPowerEventData",
        "---@field charging? boolean Whether the current power source is charging.",
        "",
        "---@class EasyBarAudioEventData",
        "---@field muted? boolean Whether the current audio output is muted.",
        "---@field value? number The current audio-related value when provided.",
        "",
        "---@class EasyBarEvent",
        "---@field name string The dispatched event name.",
        "---@field widget_id? string The subscribed widget id receiving the event.",
        "---@field target_widget_id? string The concrete node id that received the interaction.",
        "---@field app_name? string The focused app name for app-switch style events.",
        "---@field button? EasyBarMouseButton|string The mouse button name, usually `left`, `right`, or `middle`.",
        "---@field direction? EasyBarScrollDirection|string The scroll direction, usually `up`, `down`, `left`, or `right`.",
        "---@field value? number|string|boolean The event value for slider and driver updates.",
        "---@field delta_x? number Horizontal scroll delta.",
        "---@field delta_y? number Vertical scroll delta.",
        "---@field network? EasyBarNetworkEventData Structured network event data.",
        "---@field power? EasyBarPowerEventData Structured power event data.",
        "---@field audio? EasyBarAudioEventData Structured audio event data.",
        "",
        "---@alias EasyBarEventHandler fun(event: EasyBarEvent)",
        "",
        "---@class EasyBarEventToken",
        "---@field name EasyBarEventName The canonical runtime event name sent by EasyBar.",
        "",
        "---@class EasyBarMouseButtons",
    ]

    for value in mouse_buttons:
        lines.append(f"---@field {value} EasyBarMouseButton")

    lines.extend(["", "---@class EasyBarScrollDirections"])
    for value in scroll_directions:
        lines.append(f"---@field {value} EasyBarScrollDirection")

    mouse = widget_groups["mouse"]
    lines.extend(["", "---@class EasyBarMouseEvents"])
    for event in mouse["events"]:
        lines.append(f'---@field {event["luaField"]}? EasyBarEventToken {event["doc"]}')
    for value in mouse_buttons:
        lines.append(
            f'---@field {value}_button EasyBarMouseButton Constant for `event.button == "{value}"`.'
        )
    for value in scroll_directions:
        lines.append(
            f'---@field {value}_scroll EasyBarScrollDirection Constant for `event.direction == "{value}"`.'
        )
    lines.extend(
        [
            "---@field buttons EasyBarMouseButtons Nested mouse-button constants.",
            "---@field directions EasyBarScrollDirections Nested scroll-direction constants.",
            "",
            "---@class EasyBarSliderEvents",
        ]
    )

    slider = widget_groups["slider"]
    for event in slider["events"]:
        lines.append(f'---@field {event["luaField"]}? EasyBarEventToken {event["doc"]}')

    lines.extend(["", "---@class EasyBarEvents"])
    lines.append(f'---@field {forced["luaField"]}? EasyBarEventToken {forced["doc"]}')
    for event in app_events:
        lines.append(f'---@field {event["luaField"]}? EasyBarEventToken {event["doc"]}')
    for group in manifest["widgetGroups"]:
        lines.append(f'---@field {group["name"]}? EasyBar{group["name"].title()}Events {group["doc"]}')

    lines.append("")
    return "\n".join(lines)


def rebuild_lua_api_stub(manifest: dict) -> None:
    generated_events = render_lua_api_block(manifest)
    LUA_API_EVENTS_PATH.write_text(generated_events)

    base = LUA_API_BASE_PATH.read_text()
    if LUA_API_INSERT_MARKER not in base:
        raise RuntimeError("could not find generated event API insertion marker in easybar_api.base.lua")

    combined = base.replace(LUA_API_INSERT_MARKER, generated_events, 1).rstrip()
    LUA_API_STUB_PATH.write_text(f"{combined}\n")


def main() -> None:
    manifest = load_manifest()
    EVENT_TOKENS_PATH.write_text(render_event_tokens(manifest))
    rebuild_lua_api_stub(manifest)


if __name__ == "__main__":
    main()
