import Foundation

extension BuiltinNativeNodeFactory {
  /// Builds one root node with the shared built-in style defaults.
  static func makeRootNode(
    id: String,
    kind: WidgetNodeKind,
    placement: Config.BuiltinWidgetPlacement,
    style: Config.BuiltinWidgetStyle,
    icon: String = "",
    text: String = "",
    color: String? = nil,
    value: Double? = nil,
    min: Double? = nil,
    max: Double? = nil,
    step: Double? = nil
  ) -> WidgetNodeState {
    makeNode(
      id: id,
      root: id,
      kind: kind,
      parent: placement.groupID,
      position: placement.position,
      order: placement.order,
      icon: icon,
      text: text,
      color: color,
      value: value,
      min: min,
      max: max,
      step: step,
      paddingX: style.paddingX,
      paddingY: style.paddingY,
      marginX: style.marginX,
      marginY: style.marginY,
      spacing: style.spacing,
      backgroundColor: style.backgroundColorHex,
      borderColor: style.borderColorHex,
      borderWidth: style.borderWidth,
      cornerRadius: style.cornerRadius,
      opacity: style.opacity
    )
  }

  /// Builds one child node with the shared child defaults.
  static func makeChildNode(
    id: String,
    root: String,
    kind: WidgetNodeKind,
    parent: String,
    position: WidgetPosition,
    order: Int,
    icon: String = "",
    text: String = "",
    color: String? = nil,
    iconColor: String? = nil,
    labelColor: String? = nil,
    visible: Bool = true,
    role: WidgetNodeRole? = nil,
    imagePath: String? = nil,
    imageSize: Double? = nil,
    imageCornerRadius: Double? = nil,
    symbolName: String? = nil,
    symbolSecondaryColor: String? = nil,
    symbolOverlayName: String? = nil,
    symbolOverlayColor: String? = nil,
    symbolOverlayBackdropColor: String? = nil,
    symbolOverlayScale: Double? = nil,
    symbolOverlayBackdropScale: Double? = nil,
    symbolOverlayOffsetX: Double? = nil,
    symbolOverlayOffsetY: Double? = nil,
    symbolFillFraction: Double? = nil,
    symbolFillWidthFactor: Double? = nil,
    symbolFillHeightFactor: Double? = nil,
    symbolFillOffsetXFactor: Double? = nil,
    symbolFillOffsetYFactor: Double? = nil,
    symbolFillCornerRadiusFactor: Double? = nil,
    symbolFillMinimumVisibleWidthFactor: Double? = nil,
    symbolCanvasWidthFactor: Double? = nil,
    symbolCanvasHeightFactor: Double? = nil,
    fontSize: Double? = nil,
    iconFontSize: Double? = nil,
    labelFontSize: Double? = nil,
    iconOffsetX: Double? = nil,
    iconOffsetY: Double? = nil,
    value: Double? = nil,
    min: Double? = nil,
    max: Double? = nil,
    step: Double? = nil,
    paddingX: Double? = 0,
    paddingY: Double? = 0,
    marginX: Double? = nil,
    marginY: Double? = nil,
    spacing: Double? = 4,
    backgroundColor: String? = nil,
    borderColor: String? = nil,
    borderWidth: Double? = nil,
    cornerRadius: Double? = nil,
    opacity: Double? = 1,
    width: Double? = nil,
    height: Double? = nil
  ) -> WidgetNodeState {
    makeNode(
      id: id,
      root: root,
      kind: kind,
      parent: parent,
      position: position,
      order: order,
      icon: icon,
      text: text,
      color: color,
      iconColor: iconColor,
      labelColor: labelColor,
      visible: visible,
      role: role,
      imagePath: imagePath,
      imageSize: imageSize,
      imageCornerRadius: imageCornerRadius,
      symbolName: symbolName,
      symbolSecondaryColor: symbolSecondaryColor,
      symbolOverlayName: symbolOverlayName,
      symbolOverlayColor: symbolOverlayColor,
      symbolOverlayBackdropColor: symbolOverlayBackdropColor,
      symbolOverlayScale: symbolOverlayScale,
      symbolOverlayBackdropScale: symbolOverlayBackdropScale,
      symbolOverlayOffsetX: symbolOverlayOffsetX,
      symbolOverlayOffsetY: symbolOverlayOffsetY,
      symbolFillFraction: symbolFillFraction,
      symbolFillWidthFactor: symbolFillWidthFactor,
      symbolFillHeightFactor: symbolFillHeightFactor,
      symbolFillOffsetXFactor: symbolFillOffsetXFactor,
      symbolFillOffsetYFactor: symbolFillOffsetYFactor,
      symbolFillCornerRadiusFactor: symbolFillCornerRadiusFactor,
      symbolFillMinimumVisibleWidthFactor: symbolFillMinimumVisibleWidthFactor,
      symbolCanvasWidthFactor: symbolCanvasWidthFactor,
      symbolCanvasHeightFactor: symbolCanvasHeightFactor,
      fontSize: fontSize,
      iconFontSize: iconFontSize,
      labelFontSize: labelFontSize,
      iconOffsetX: iconOffsetX,
      iconOffsetY: iconOffsetY,
      value: value,
      min: min,
      max: max,
      step: step,
      paddingX: paddingX,
      paddingY: paddingY,
      marginX: marginX,
      marginY: marginY,
      spacing: spacing,
      backgroundColor: backgroundColor,
      borderColor: borderColor,
      borderWidth: borderWidth,
      cornerRadius: cornerRadius,
      opacity: opacity,
      width: width,
      height: height
    )
  }

  /// Builds one node with the shared built-in defaults applied.
  static func makeNode(
    id: String,
    root: String,
    kind: WidgetNodeKind,
    parent: String?,
    position: WidgetPosition,
    order: Int,
    icon: String = "",
    text: String = "",
    color: String? = nil,
    iconColor: String? = nil,
    labelColor: String? = nil,
    visible: Bool = true,
    role: WidgetNodeRole? = nil,
    imagePath: String? = nil,
    imageSize: Double? = nil,
    imageCornerRadius: Double? = nil,
    symbolName: String? = nil,
    symbolSecondaryColor: String? = nil,
    symbolOverlayName: String? = nil,
    symbolOverlayColor: String? = nil,
    symbolOverlayBackdropColor: String? = nil,
    symbolOverlayScale: Double? = nil,
    symbolOverlayBackdropScale: Double? = nil,
    symbolOverlayOffsetX: Double? = nil,
    symbolOverlayOffsetY: Double? = nil,
    symbolFillFraction: Double? = nil,
    symbolFillWidthFactor: Double? = nil,
    symbolFillHeightFactor: Double? = nil,
    symbolFillOffsetXFactor: Double? = nil,
    symbolFillOffsetYFactor: Double? = nil,
    symbolFillCornerRadiusFactor: Double? = nil,
    symbolFillMinimumVisibleWidthFactor: Double? = nil,
    symbolCanvasWidthFactor: Double? = nil,
    symbolCanvasHeightFactor: Double? = nil,
    fontSize: Double? = nil,
    iconFontSize: Double? = nil,
    labelFontSize: Double? = nil,
    iconOffsetX: Double? = nil,
    iconOffsetY: Double? = nil,
    value: Double? = nil,
    min: Double? = nil,
    max: Double? = nil,
    step: Double? = nil,
    paddingX: Double? = 0,
    paddingY: Double? = 0,
    marginX: Double? = nil,
    marginY: Double? = nil,
    spacing: Double? = 4,
    backgroundColor: String? = nil,
    borderColor: String? = nil,
    borderWidth: Double? = nil,
    cornerRadius: Double? = nil,
    opacity: Double? = 1,
    width: Double? = nil,
    height: Double? = nil
  ) -> WidgetNodeState {
    WidgetNodeState(
      id: id,
      root: root,
      kind: kind,
      parent: parent,
      position: position,
      order: order,
      icon: icon,
      text: text,
      color: color,
      iconColor: iconColor,
      labelColor: labelColor,
      visible: visible,
      role: role,
      receivesMouseHover: nil,
      receivesMouseDown: nil,
      receivesMouseUp: nil,
      receivesMouseClick: nil,
      receivesMouseScroll: nil,
      imagePath: imagePath,
      imageSize: imageSize,
      imageCornerRadius: imageCornerRadius,
      symbolName: symbolName,
      symbolSecondaryColor: symbolSecondaryColor,
      symbolOverlayName: symbolOverlayName,
      symbolOverlayColor: symbolOverlayColor,
      symbolOverlayBackdropColor: symbolOverlayBackdropColor,
      symbolOverlayScale: symbolOverlayScale,
      symbolOverlayBackdropScale: symbolOverlayBackdropScale,
      symbolOverlayOffsetX: symbolOverlayOffsetX,
      symbolOverlayOffsetY: symbolOverlayOffsetY,
      symbolFillFraction: symbolFillFraction,
      symbolFillWidthFactor: symbolFillWidthFactor,
      symbolFillHeightFactor: symbolFillHeightFactor,
      symbolFillOffsetXFactor: symbolFillOffsetXFactor,
      symbolFillOffsetYFactor: symbolFillOffsetYFactor,
      symbolFillCornerRadiusFactor: symbolFillCornerRadiusFactor,
      symbolFillMinimumVisibleWidthFactor: symbolFillMinimumVisibleWidthFactor,
      symbolCanvasWidthFactor: symbolCanvasWidthFactor,
      symbolCanvasHeightFactor: symbolCanvasHeightFactor,
      fontSize: fontSize,
      iconFontSize: iconFontSize,
      labelFontSize: labelFontSize,
      iconOffsetX: iconOffsetX,
      iconOffsetY: iconOffsetY,
      value: value,
      min: min,
      max: max,
      step: step,
      values: nil,
      lineWidth: nil,
      paddingX: paddingX,
      paddingY: paddingY,
      paddingLeft: nil,
      paddingRight: nil,
      paddingTop: nil,
      paddingBottom: nil,
      marginX: marginX,
      marginY: marginY,
      marginLeft: nil,
      marginRight: nil,
      marginTop: nil,
      marginBottom: nil,
      spacing: spacing,
      backgroundColor: backgroundColor,
      borderColor: borderColor,
      borderWidth: borderWidth,
      cornerRadius: cornerRadius,
      opacity: opacity,
      width: width,
      height: height,
      yOffset: nil
    )
  }
}
